// Generated by scripts/gen_macro_stub.py from macro/warp_g1/warp_g1.v; do not edit.
// Idle model of the fabric macro `warp_g1` for the black-box test mode (test/Makefile):
// every output 0, as a fabric whose design drives nothing. Not used for synthesis.
`default_nettype none

module warp_g1 (
    input  wire Tile_X1Y0_A_OUT_top,
    output wire Tile_X1Y0_A_IN_top,
    output wire Tile_X1Y0_A_EN_top,
    input  wire Tile_X2Y0_A_OUT_top,
    output wire Tile_X2Y0_A_IN_top,
    output wire Tile_X2Y0_A_EN_top,
    input  wire Tile_X3Y0_A_OUT_top,
    output wire Tile_X3Y0_A_IN_top,
    output wire Tile_X3Y0_A_EN_top,
    input  wire Tile_X4Y0_A_OUT_top,
    output wire Tile_X4Y0_A_IN_top,
    output wire Tile_X4Y0_A_EN_top,
    input  wire Tile_X0Y1_A_OUT_top,
    output wire Tile_X0Y1_A_IN_top,
    output wire Tile_X0Y1_A_EN_top,
    input  wire Tile_X0Y1_B_OUT_top,
    output wire Tile_X0Y1_B_IN_top,
    output wire Tile_X0Y1_B_EN_top,
    input  wire Tile_X0Y1_C_OUT_top,
    output wire Tile_X0Y1_C_IN_top,
    output wire Tile_X0Y1_C_EN_top,
    input  wire Tile_X0Y1_D_OUT_top,
    output wire Tile_X0Y1_D_IN_top,
    output wire Tile_X0Y1_D_EN_top,
    input  wire Tile_X5Y1_A_OUT_top,
    output wire Tile_X5Y1_A_IN_top,
    output wire Tile_X5Y1_A_EN_top,
    input  wire Tile_X5Y1_B_OUT_top,
    output wire Tile_X5Y1_B_IN_top,
    output wire Tile_X5Y1_B_EN_top,
    input  wire Tile_X5Y1_C_OUT_top,
    output wire Tile_X5Y1_C_IN_top,
    output wire Tile_X5Y1_C_EN_top,
    input  wire Tile_X5Y1_D_OUT_top,
    output wire Tile_X5Y1_D_IN_top,
    output wire Tile_X5Y1_D_EN_top,
    input  wire Tile_X0Y2_A_OUT_top,
    output wire Tile_X0Y2_A_IN_top,
    output wire Tile_X0Y2_A_EN_top,
    input  wire Tile_X0Y2_B_OUT_top,
    output wire Tile_X0Y2_B_IN_top,
    output wire Tile_X0Y2_B_EN_top,
    input  wire Tile_X0Y2_C_OUT_top,
    output wire Tile_X0Y2_C_IN_top,
    output wire Tile_X0Y2_C_EN_top,
    input  wire Tile_X0Y2_D_OUT_top,
    output wire Tile_X0Y2_D_IN_top,
    output wire Tile_X0Y2_D_EN_top,
    input  wire Tile_X5Y2_A_OUT_top,
    output wire Tile_X5Y2_A_IN_top,
    output wire Tile_X5Y2_A_EN_top,
    input  wire Tile_X5Y2_B_OUT_top,
    output wire Tile_X5Y2_B_IN_top,
    output wire Tile_X5Y2_B_EN_top,
    input  wire Tile_X5Y2_C_OUT_top,
    output wire Tile_X5Y2_C_IN_top,
    output wire Tile_X5Y2_C_EN_top,
    input  wire Tile_X5Y2_D_OUT_top,
    output wire Tile_X5Y2_D_IN_top,
    output wire Tile_X5Y2_D_EN_top,
    input  wire Tile_X0Y3_A_OUT_top,
    output wire Tile_X0Y3_A_IN_top,
    output wire Tile_X0Y3_A_EN_top,
    input  wire Tile_X0Y3_B_OUT_top,
    output wire Tile_X0Y3_B_IN_top,
    output wire Tile_X0Y3_B_EN_top,
    input  wire Tile_X0Y3_C_OUT_top,
    output wire Tile_X0Y3_C_IN_top,
    output wire Tile_X0Y3_C_EN_top,
    input  wire Tile_X0Y3_D_OUT_top,
    output wire Tile_X0Y3_D_IN_top,
    output wire Tile_X0Y3_D_EN_top,
    input  wire Tile_X5Y3_A_OUT_top,
    output wire Tile_X5Y3_A_IN_top,
    output wire Tile_X5Y3_A_EN_top,
    input  wire Tile_X5Y3_B_OUT_top,
    output wire Tile_X5Y3_B_IN_top,
    output wire Tile_X5Y3_B_EN_top,
    input  wire Tile_X5Y3_C_OUT_top,
    output wire Tile_X5Y3_C_IN_top,
    output wire Tile_X5Y3_C_EN_top,
    input  wire Tile_X5Y3_D_OUT_top,
    output wire Tile_X5Y3_D_IN_top,
    output wire Tile_X5Y3_D_EN_top,
    input  wire Tile_X0Y4_SYS_RESET_RESET_top,
    input  wire Tile_X1Y4_A_OUT_top,
    output wire Tile_X1Y4_A_IN_top,
    output wire Tile_X1Y4_A_EN_top,
    input  wire Tile_X1Y4_B_OUT_top,
    output wire Tile_X1Y4_B_IN_top,
    output wire Tile_X1Y4_B_EN_top,
    input  wire Tile_X2Y4_A_OUT_top,
    output wire Tile_X2Y4_A_IN_top,
    output wire Tile_X2Y4_A_EN_top,
    input  wire Tile_X2Y4_B_OUT_top,
    output wire Tile_X2Y4_B_IN_top,
    output wire Tile_X2Y4_B_EN_top,
    input  wire Tile_X3Y4_A_OUT_top,
    output wire Tile_X3Y4_A_IN_top,
    output wire Tile_X3Y4_A_EN_top,
    input  wire Tile_X3Y4_B_OUT_top,
    output wire Tile_X3Y4_B_IN_top,
    output wire Tile_X3Y4_B_EN_top,
    input  wire Tile_X4Y4_A_OUT_top,
    output wire Tile_X4Y4_A_IN_top,
    output wire Tile_X4Y4_A_EN_top,
    input  wire Tile_X4Y4_B_OUT_top,
    output wire Tile_X4Y4_B_IN_top,
    output wire Tile_X4Y4_B_EN_top,
    input  wire [159:0] FrameData,
    input  wire [119:0] FrameStrobe
);
    assign Tile_X1Y0_A_IN_top = 1'd0;
    assign Tile_X1Y0_A_EN_top = 1'd0;
    assign Tile_X2Y0_A_IN_top = 1'd0;
    assign Tile_X2Y0_A_EN_top = 1'd0;
    assign Tile_X3Y0_A_IN_top = 1'd0;
    assign Tile_X3Y0_A_EN_top = 1'd0;
    assign Tile_X4Y0_A_IN_top = 1'd0;
    assign Tile_X4Y0_A_EN_top = 1'd0;
    assign Tile_X0Y1_A_IN_top = 1'd0;
    assign Tile_X0Y1_A_EN_top = 1'd0;
    assign Tile_X0Y1_B_IN_top = 1'd0;
    assign Tile_X0Y1_B_EN_top = 1'd0;
    assign Tile_X0Y1_C_IN_top = 1'd0;
    assign Tile_X0Y1_C_EN_top = 1'd0;
    assign Tile_X0Y1_D_IN_top = 1'd0;
    assign Tile_X0Y1_D_EN_top = 1'd0;
    assign Tile_X5Y1_A_IN_top = 1'd0;
    assign Tile_X5Y1_A_EN_top = 1'd0;
    assign Tile_X5Y1_B_IN_top = 1'd0;
    assign Tile_X5Y1_B_EN_top = 1'd0;
    assign Tile_X5Y1_C_IN_top = 1'd0;
    assign Tile_X5Y1_C_EN_top = 1'd0;
    assign Tile_X5Y1_D_IN_top = 1'd0;
    assign Tile_X5Y1_D_EN_top = 1'd0;
    assign Tile_X0Y2_A_IN_top = 1'd0;
    assign Tile_X0Y2_A_EN_top = 1'd0;
    assign Tile_X0Y2_B_IN_top = 1'd0;
    assign Tile_X0Y2_B_EN_top = 1'd0;
    assign Tile_X0Y2_C_IN_top = 1'd0;
    assign Tile_X0Y2_C_EN_top = 1'd0;
    assign Tile_X0Y2_D_IN_top = 1'd0;
    assign Tile_X0Y2_D_EN_top = 1'd0;
    assign Tile_X5Y2_A_IN_top = 1'd0;
    assign Tile_X5Y2_A_EN_top = 1'd0;
    assign Tile_X5Y2_B_IN_top = 1'd0;
    assign Tile_X5Y2_B_EN_top = 1'd0;
    assign Tile_X5Y2_C_IN_top = 1'd0;
    assign Tile_X5Y2_C_EN_top = 1'd0;
    assign Tile_X5Y2_D_IN_top = 1'd0;
    assign Tile_X5Y2_D_EN_top = 1'd0;
    assign Tile_X0Y3_A_IN_top = 1'd0;
    assign Tile_X0Y3_A_EN_top = 1'd0;
    assign Tile_X0Y3_B_IN_top = 1'd0;
    assign Tile_X0Y3_B_EN_top = 1'd0;
    assign Tile_X0Y3_C_IN_top = 1'd0;
    assign Tile_X0Y3_C_EN_top = 1'd0;
    assign Tile_X0Y3_D_IN_top = 1'd0;
    assign Tile_X0Y3_D_EN_top = 1'd0;
    assign Tile_X5Y3_A_IN_top = 1'd0;
    assign Tile_X5Y3_A_EN_top = 1'd0;
    assign Tile_X5Y3_B_IN_top = 1'd0;
    assign Tile_X5Y3_B_EN_top = 1'd0;
    assign Tile_X5Y3_C_IN_top = 1'd0;
    assign Tile_X5Y3_C_EN_top = 1'd0;
    assign Tile_X5Y3_D_IN_top = 1'd0;
    assign Tile_X5Y3_D_EN_top = 1'd0;
    assign Tile_X1Y4_A_IN_top = 1'd0;
    assign Tile_X1Y4_A_EN_top = 1'd0;
    assign Tile_X1Y4_B_IN_top = 1'd0;
    assign Tile_X1Y4_B_EN_top = 1'd0;
    assign Tile_X2Y4_A_IN_top = 1'd0;
    assign Tile_X2Y4_A_EN_top = 1'd0;
    assign Tile_X2Y4_B_IN_top = 1'd0;
    assign Tile_X2Y4_B_EN_top = 1'd0;
    assign Tile_X3Y4_A_IN_top = 1'd0;
    assign Tile_X3Y4_A_EN_top = 1'd0;
    assign Tile_X3Y4_B_IN_top = 1'd0;
    assign Tile_X3Y4_B_EN_top = 1'd0;
    assign Tile_X4Y4_A_IN_top = 1'd0;
    assign Tile_X4Y4_A_EN_top = 1'd0;
    assign Tile_X4Y4_B_IN_top = 1'd0;
    assign Tile_X4Y4_B_EN_top = 1'd0;
    wire _unused = &{Tile_X1Y0_A_OUT_top, Tile_X2Y0_A_OUT_top, Tile_X3Y0_A_OUT_top, Tile_X4Y0_A_OUT_top, Tile_X0Y1_A_OUT_top, Tile_X0Y1_B_OUT_top, Tile_X0Y1_C_OUT_top, Tile_X0Y1_D_OUT_top, Tile_X5Y1_A_OUT_top, Tile_X5Y1_B_OUT_top, Tile_X5Y1_C_OUT_top, Tile_X5Y1_D_OUT_top, Tile_X0Y2_A_OUT_top, Tile_X0Y2_B_OUT_top, Tile_X0Y2_C_OUT_top, Tile_X0Y2_D_OUT_top, Tile_X5Y2_A_OUT_top, Tile_X5Y2_B_OUT_top, Tile_X5Y2_C_OUT_top, Tile_X5Y2_D_OUT_top, Tile_X0Y3_A_OUT_top, Tile_X0Y3_B_OUT_top, Tile_X0Y3_C_OUT_top, Tile_X0Y3_D_OUT_top, Tile_X5Y3_A_OUT_top, Tile_X5Y3_B_OUT_top, Tile_X5Y3_C_OUT_top, Tile_X5Y3_D_OUT_top, Tile_X0Y4_SYS_RESET_RESET_top, Tile_X1Y4_A_OUT_top, Tile_X1Y4_B_OUT_top, Tile_X2Y4_A_OUT_top, Tile_X2Y4_B_OUT_top, Tile_X3Y4_A_OUT_top, Tile_X3Y4_B_OUT_top, Tile_X4Y4_A_OUT_top, Tile_X4Y4_B_OUT_top, FrameData, FrameStrobe, 1'b0};
endmodule
