#!/usr/bin/env bash
# L7-style mutation check of the pin unit: each mutant is one injected bug in a copy of src/; the L1
# suite must fail on every one. Usage (in the venv): [FULL=1] [ONLY=<text>] test_internal/pin/mutate.sh
# (the milestone B mutants, labelled "B1:" to "B3:", need FULL=1: FULL=1 ONLY=B3 test_internal/pin/mutate.sh)
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
WORK="$(mktemp -d)"
# file # sed expression # what it breaks
MUTANTS=(
  "trw_pin_tx.v#s/(!m_pulse \&\& tail \&\& (bt_i <= 16'd1))/(!m_pulse \&\& tail \&\& (bt_i == 16'd0))/#P3: take one clock late after a shift"
  "trw_pin_tx.v#s/assign late_set = tk_late/assign late_set = 1'b0 \&\& tk_late/#P4: LATE never set"
  "trw_pin_tx.v#s/wire \[FRAC-1:0\] p_frac = tk_late ? {FRAC{1'b0}} : cf_b;/wire [FRAC-1:0] p_frac = {FRAC{1'b0}};/#P4: cursor fraction dropped"
  "trw_pin_rx.v#s/wire taint = ftaint_b || echo;/wire taint = ftaint_b;/#P13: echo taint ignored"
  "trw_pin_rx.v#s/wire ev = edge_ok \&\& qual_ok;/wire ev = edge_ok;/#P8: EV_QUAL ignored"
  "trw_pin_rx.v#s/(want \&\& !rx_free) || //#4.5: OVERRUN on a full producer"
  "trw_pin_tx.v#s/end else if (!p_first \&\& stretch) begin/end else if (1'b0) begin/#P11: STRETCH ignored"
  "trw_pin_tx.v#s/lk_pre <= tk \&\& h_lk \&\& tx_preload/lk_pre <= 1'b0 \&\& tx_preload/#P9: preload ignored"
  "trw_pin_tx.v#s/wire lk_abort = linked \&\& sel_fall/wire lk_abort = 1'b0 \&\& sel_fall/#P15: deselect abort ignored"
  "trw_pin_rx.v#s/wire \[RW-1:0\] rt_cur = start ? sofs : rt;/wire [RW-1:0] rt_cur = start ? sofs + 24'd256 : rt;/#P5: sample one clock late"
  "trw_pin_tx.v#s/wire w_fire = w_v \&\& (w_rise ? b_rise : b_fall);/wire w_fire = w_v \&\& (b_rise || b_fall);/#P16: WAIT on either edge"
  "trw_pin_tx.v#s/wire \[0:0\] nlvx = d_hi ? (d_hi_v ^ idle) : due_lvl_v ? (due_lvl ^ idle) : d_lo ? 1'b0 : lvx;/wire [0:0] nlvx = d_hi ? (d_hi_v ^ idle) : d_lo ? 1'b0 : due_lvl_v ? (due_lvl ^ idle) : lvx;/#P4: return-to-IDLE beats a LEVEL on its edge"
  "trw_pin_tx.v#s/    wire clk_run = m_clk \&\& p_act; /    wire clk_run = m_clk \&\& p_act \&\& !p_end; /#P34: a CLK in the release clock starts a new burst"
  "trw_pin_rx.v#s/    wire        evr      = ev \&\& ev_reset;/    wire        evr      = 1'b0;/; s/    wire rst_fr = !sel || rxset; /    wire rst_fr = !sel || rxset || (ev \&\& ev_reset); /#P38: EV_RESET after the event clock's sample"
  "trw_pin_tx.v#s/    wire linked  = m_shift \&\& ((tx_edge == \`TRW_PCE_TX_EDGE_RISE) || (tx_edge == \`TRW_PCE_TX_EDGE_FALL));/    wire linked  = m_shift \&\& (tx_edge != 2'd0);/#P43: TX_EDGE 3 acts as linked"
  "trw_pin_tx.v#s/                else if (lk_idle || (lk_edge/                else if (due_lvl_v || lk_idle || (lk_edge/#P44: a LEVEL cancels the pending return to IDLE"
  "trw_pin_tx.v#s/    wire d_hi_v = (s_bit || lk_bit) ? bit_o : pb1 ? pl_first : pb2 ? !pl_first : (ph ? !idle : idle);/    wire d_hi_v = (s_bit || lk_bit) ? bit_o : pb1 ? pl_first : pb2 ? pl_first : (ph ? !idle : idle);/#B1: P17 PULSE second level not inverted"
  "trw_pin_tx.v#s/                    ps    <= (p_tn == 12'd0) ? 8'd0 : presc;/                    ps    <= 8'd0;/#B1: P17 PULSE phases ignore PRESC"
  "trw_pin_tx.v#s/                || (p_tail \&\& (pt == 12'd0) \&\& (ps <= 8'd1)) || (p_lastb \&\& p_t2one);/                ;/#B1: P17 back-to-back PULSE tokens leave a gap"
  "trw_pin_tx.v#s/            end else if (!lvx) begin/            end else if (1'b0) begin/#B1: P30 carrier phase does not restart"
  "trw_pin_tx.v#s/                ct  <= ct + {1'b0, carrier} - 25'd512;/                ct  <= {ct[24:9], 9'd0} + {1'b0, carrier} - 25'd512;/#B1: P30 carrier fraction dropped"
  "trw_pin_tx.v#s/    wire m_pulse = (FULL != 0) \&\& (txmode == \`TRW_PCE_TXMODE_PULSE);/    wire m_pulse = (txmode == \`TRW_PCE_TXMODE_PULSE);/#B1: D-040 a lean unit runs PULSE"
  "trw_pin_bs.v#s/    wire        rs_do = rs_edge \&\& (d != 25'd0);/    wire        rs_do = 1'b0 \&\& rs_edge \&\& (d != 25'd0);/#B2: P22 no resync"
  "trw_pin_bs.v#s/    wire hsync   = f_start;/    wire hsync   = 1'b0;/#B2: P21 no hard sync of the bit clock"
  "trw_pin_bs.v#s/    wire        done = !hsync \&\& smp_done;/    wire        done = smp_done;/#B2: P21 hard sync does not re-arm the sample"
  "trw_pin_bs.v#s/    wire        goes_idle = smp \&\& rec \&\& (icnt_r >= idle_bits)/    wire        goes_idle = 1'b0 \&\& smp \&\& rec \&\& (icnt_r >= idle_bits)/#B2: P20 idle never ends a frame"
  "trw_pin_bs.v#s/    wire \[15:0\] w1       = order ? {w\[14:0\], cbit} : (w | ({15'd0, cbit} << wn));/    wire [15:0] w1       = {w[14:0], cbit};/#B2: RX word ORDER ignored"
  "trw_pin_bs.v#s/    wire \[24:0\] d    = !smp_done ? ((e < sj) ? e : sj)/    wire [24:0] d    = !smp_done ? sj/#B2: P22 resync moves by SJW, not by the phase error"
  "trw_pin_bs.v#s/    wire        fbit     = smp \&\& in_frame \&\& !goes_idle \&\& !se0_s;/    wire        fbit     = smp \&\& in_frame \&\& !se0_s;/#B2: P-G29 the idle-making sample completes a word"
  "trw_pin_bs.v#s/    wire        dbit     = fbit \&\& !s_due \&\& !f6 \&\& open_fr;/    wire        dbit     = fbit \&\& !s_err \&\& !f6 \&\& open_fr;/#B2: P23 stuff bits not removed"
  "trw_pin_bs.v#s/    wire        s_err    = fbit \&\& s_due \&\& run_eq \&\& !dlf;/    wire        s_err    = 1'b0;/#B2: P23 stuff errors not detected"
  "trw_pin_bs.v#s/crc\[ctop\] ? crc_poly : 16'd0/crc[ctop] ? 16'd1 : 16'd0/g#B2: P24 CRC polynomial ignored"
  "trw_pin_bs.v#s/    wire        n_tok    = at_n \&\& words_on;/    wire        n_tok    = 1'b0;/#B2: P24 no verdict at FRAME's n"
  "trw_pin_bs.v#s/                        post     <= 1'b1;/                        post     <= 1'b0;/#B2: P24 no stuff check right after bit n"
  "trw_pin_bs.v#s/    wire        lvl_ok   = !stuff_lvl\[1\] || (rl == stuff_lvl\[0\]);/    wire        lvl_ok   = 1'b1;/#B2: P23 STUFF_LVL ignored"
  "trw_pin_bs.v#s/    wire        c_in     = cm \&\& (dcnt >= {6'd0, crc_skip})/    wire        c_in     = cm/#B2: P24 CRC_SKIP ignored"
  "trw_pin_bs.v#s/    assign late_set = f_now \&\& (!in_frame || !words_on || (dcnt >= arg\[10:0\]));/    assign late_set = 1'b0;/#B2: P24 FRAME never LATE"
  "trw_pin_bs.v#s/    wire own_lvl = drv \&\& (a_in == tlv);/    wire own_lvl = 1'b0;/#B2: P22 resync on the echo of our own edges"
  "trw_pin_bs.v#s/(idle_bits != 5'd0) \&\& !drv \&\&/(idle_bits != 5'd0) \&\&/#B2: P20 idle ends a frame while we drive a bit"
  "trw_pin_bs.v#s/    wire        jn       = f_start/    wire        jn       = 1'b0 \&\& f_start/#B2: P21 no join of another node's frame start"
  "trw_pin_bs.v#s/(q_any \&\& (!sync_p || bus_idle))/q_any/#B2: P21 a SYNC frame does not wait for bus idle"
  "trw_pin_bs.v#s/            if (f_start || o_start) begin/            if (f_start) begin/#B2: P21 our frame start left to the echo (hard sync on our own edge)"
  "trw_pin_bs.v#s/    wire        sync_ev  = (o_start \&\& sync_p) || jn;/    wire        sync_ev  = 1'b0;/#B2: P21 no EVENT 0x9001"
  "trw_pin_bs.v#s/    wire        ts_due   = ts_on \&\&/    wire        ts_due   = 1'b0 \&\& ts_on \&\&/#B2: P25 no TX stuffing"
  "trw_pin_bs.v#s/                ts_on <= arg\[2\];/                ts_on <= arg[2];  if (!arg[2]) ts_p <= 1'b0;/#B2: P25 a LINE drops the stuff bit due before it"
  "trw_pin_bs.v#s/k_crc ? ((crc_src ^ crc_xor) \& cmask)/k_crc ? (crc_src \& cmask)/#B2: P25 CRC_XOR ignored"
  "trw_pin_bs.v#s/    wire \[15:0\] crc_src  = arg\[6\] ? (crc_init \& cmask) : tcrc;/    wire [15:0] crc_src  = tcrc;/#B2: P25 LINE [3] before [6]"
  "trw_pin_bs.v#s/                if (arg\[6\])$/                if (1'b0)/#B2: P25 LINE [6] does not reset the TX CRC"
  "trw_pin_bs.v#s/q <= ld_q;  q_hi <= order;/q <= ld_q;  q_hi <= 1'b1;/#B2: P25 TX ORDER ignored"
  "trw_pin_bs.v#s/    wire \[4:0\]  nb       = (tx_lentok ? /    wire [4:0]  nb       = (1'b0 ? /#B2: P25 TX_LENTOK ignored"
  "trw_pin_bs.v#s/    wire        tx_ok   = (qn == 5'd0) \&\& /    wire        tx_ok   = /#B2: P25 a TX token taken while bits are queued"
  "trw_pin_bs.v#s/            if (k_wait) begin/            if (1'b0) begin/#B2: P25 WAIT [1] ignored"
  "trw_pin_bs.v#s/\&\& !jq \&\& (!wt_p || smp);/\&\& !jq \&\& !wt_p;/#B2: P-G31 WAIT [1] releases a clock after the sample point"
  "trw_pin_bs.v#s/    wire        rb_lose  = rb_s/    wire        rb_lose  = 1'b0 \&\& rb_s/#B3: P26 no arbitration loss"
  "trw_pin_bs.v#s/    wire        stop     = rb_lose || rb_err/    wire        stop     = rb_err/#B3: P26 losing arbitration does not stop our TX"
  "trw_pin_bs.v#s/sq <= 5'd0;  jq <= 1'b0;  dsc <= 1'b1;$/sq <= 5'd0;  jq <= 1'b0;/#B3: P26 tokens after an abort not discarded"
  "trw_pin_bs.v#s/    wire        rb_err   = (rb_rep \&\& !mism)/    wire        rb_err   = (rb_rep \&\& mism)/#B3: P26 mode 2 error when overridden"
  "trw_pin_bs.v#s/    wire        rb_bit   = rb_s \&\& (tmode == 2'd3) \&\& mism;/    wire        rb_bit   = 1'b0;/#B3: P26 no strict bit error"
  "trw_pin_bs.v#s/tmode \([!=]=\) 2/rbm \1 2/g#B3: P26 readback uses the current LINE mode, not the bit's"
  "trw_pin_bs.v#s/{1'b1, a_in, tmode != 2'd1/{1'b1, 1'b0, tmode != 2'd1/#B3: P26 the EVENT's level bit"
  "trw_pin_bs.v#s/            if (k_sync \&\& !txoff) begin/            if (k_sync \&\& !txoff \&\& !dsc) begin/#B3: P26 SYNC does not re-arm after an abort"
  "trw_pin_bs.v#s/            if (err_any \&\& av \&\& !txoff)/            if (1'b0)/#B3: P28 armed JAM never fires"
  "trw_pin_bs.v#s/                av <= 1'b0;  af <= 1'b0;$/                af <= 1'b0;/#B3: P28 disarm ignored"
  "trw_pin_bs.v#s/jdv <= 1'b1;  jb <= an;/jdv <= 1'b1;  jb <= 4'd0;/#B3: P28 armed JAM length ignored"
  "trw_pin_bs.v#s/jc <= {1'b0, arg\[7:6\]} + 3'd1;/jc <= 3'd1;/#B3: P28 JAM d ignored"
  "trw_pin_bs.v#s/            if (smp \&\& !s_bit \&\& jp/            if (smp \&\& jp/#B3: P28 JAM counts stuff bits"
  "trw_pin_bs.v#s/\&\& !arg\[4\] \&\& !own \&\& !txoff;/\&\& !arg[4] \&\& !txoff;/#B3: P28 a response JAM fires in our own frame"
  "trw_pin_bs.v#s/\&\& !arg\[4\] \&\& !own \&\& !txoff;/\&\& !arg[4] \&\& !own;/#B3: P28 a response JAM fires in listen-only"
  "trw_pin_bs.v#s/            if (jm_rsp) begin/            if (jm_rsp \&\& !jp) begin/#B3: P28 a new JAM does not replace a pending one"
  "trw_pin_bs.v#s/    wire        ref_ev   = k_sync \&\& txoff;/    wire        ref_ev   = 1'b0;/#B3: P28 no EVENT 0xC001"
  "trw_pin_bs.v#s/txoff <= 1'b1;  dsc <= 1'b1;/txoff <= 1'b1;/#B3: P28 listen-only does not discard"
  "trw_pin_bs.v#s/    wire        jm_off  = k_jam \&\& arg\[1\];/    wire        jm_off  = k_jam \&\& arg[1] \&\& !arg[2];/#B3: P28 [2] wins over [1]"
  "trw_pin_bs.v#s/    wire        fl_s     = fbit \&\& f6 \&\& !run_eq;/    wire        fl_s     = 1'b0;/#B3: P27 no flag"
  "trw_pin_bs.v#s/    wire        ab_tok   = ab_s \&\& words_on \&\& (dcnt != 11'd0);/    wire        ab_tok   = 1'b0;/#B3: P27 no abort ERR"
  "trw_pin_bs.v#s/    wire        cm       = dbit \&\& (!dlf || hb_full);/    wire        cm       = dbit;/; s/    wire        cbit     = dlf ? hb\[stuff_n\] : bit_in;/    wire        cbit     = bit_in;/#B3: P27 no hold-back"
  "trw_pin_bs.v#s/                    lcnt <= 11'd0;  dcnt <= 11'd0;  crc <= crc_init \& cmask;/                    lcnt <= 11'd0;  dcnt <= 11'd0;/#B3: P27 a flag keeps the CRC"
  "trw_pin_bs.v#s/    wire        bit_in   = nrzi ? (a_in == rxl) : a_in;/    wire        bit_in   = a_in;/#B3: P29 NRZI RX ignored"
  "trw_pin_bs.v#s/    wire        nl       = nrzi ? (nd ? cur : !cur) : nd;/    wire        nl       = nd;/#B3: P29 NRZI TX ignored"
  "trw_pin_unit.v#s/    assign n_out = !lvl \&\& !se0;/    assign n_out = !lvl;/#B3: P29 pin N high during SE0"
  "trw_pin_unit.v#s/((bs_on \&\& oe_auto) ? drv_b : oe)/(oe)/#B3: P29 OE_AUTO ignored"
  "trw_pin_bs.v#s/    wire        se0_s    = smp \&\& in_frame \&\& dls \&\& !a_in \&\& !b_in;/    wire        se0_s    = smp \&\& in_frame \&\& dls \&\& !a_in;/#B3: P29 SE0 ignores pin B"
  "trw_pin_bs.v#s/                            !(dls \&\& in_frame);/                            1'b1;/#B3: P29 idle ends a frame with DELIM = se0"
  "trw_pin_bs.v#s/    wire        rep_ok   = !(oe_auto \&\& own);/    wire        rep_ok   = 1'b1;/#B3: P29 our own frames reported with OE_AUTO"
  "trw_pin_bs.v#s/                    sq <= {1'b0, arg\[11:8\]} + 5'd1;/                    sq <= 5'd1;/#B3: P29 SE0 length ignored"
  "trw_pin_bs.v#s/                    jq <= 1'b1;/                    jq <= 1'b0;/#B3: P29 no J after SE0"
  "trw_pin_bs.v#s/{1'b0, own, 2'b00, vw}/{4'h0, vw}/#B3: P24 data[14] own frame missing"
  "trw_pin_bs.v#s/            if (st_hold \&\& !st_keep) begin/            if (1'b0) begin/#B3: P-G41 a status EVENT behind a frame token is lost"
)
killed=0
survived=0
for m in "${MUTANTS[@]}"; do
  IFS="#" read -r file expr what <<< "$m"
  [ -n "${ONLY:-}" ] && [[ "$what" != *"$ONLY"* ]] && continue
  # milestone B feature mutants need the full build; the D-040 fallback mutant needs the lean one
  if [ "${FULL:-0}" = 1 ]; then [[ "$what" == "B1: D-040"* ]] && continue; else [[ "$what" == B[0-9]*":"* && "$what" != "B1: D-040"* ]] && continue; fi
  rm -rf "$WORK/src"; cp -r "$ROOT/src" "$WORK/src"
  sed -i "$expr" "$WORK/src/$file"
  if cmp -s "$ROOT/src/$file" "$WORK/src/$file"; then echo "NOT APPLIED: $what"; continue; fi
  (cd "$HERE" && make FULL="${FULL:-0}" SRC_DIR="$WORK/src" SIM_BUILD="$WORK/build" COCOTB_RESULTS_FILE="$WORK/r.xml" >"$WORK/log" 2>&1)
  if grep -q "FAIL=0" "$WORK/log"; then echo "SURVIVED: $what"; survived=$((survived+1)); else
    echo "killed ($(grep -o 'FAIL=[0-9]*' "$WORK/log")): $what"; killed=$((killed+1)); fi
done
echo "mutation: $killed killed, $survived survived (FULL=${FULL:-0})"
rm -rf "$WORK"
