#!/usr/bin/env python3
"""R4 spike: generate overlay/src/r4_fabric.v, the fabric wiring, from the spec's legal sources.

The consumer ports' source lists come from tools/tripwire_spec.py (LEGAL_SOURCES, generated from
spec/tripwire.yaml, ARCHITECTURE.md §4.6), so the multiplexers are the real ones. Numbering:
  producers  0-5 U0-U5.rx, 6-11 L0.O0, L0.O1, L1.O0, L1.O1, L2.O0, L2.O1, 12 HOST_IN
  consumers  0-5 L0.I0, L0.I1, L1.I0, L1.I1, L2.I0, L2.I1, 6-11 U0-U5.tx, 12 HOST_OUT
Release (§4.4, §14 F3): all_taken[p] = AND over the ports that list p of
  !(blocking && sel == p's index in that port's list) || last_seq == p.seq.
Unit count: NU, read from `localparam NU` in overlay/src/tt_um_tripwire.v (run 2 of D-043: 4). The
numbering above stays; units NU-5 are absent: their producers are tied off in the top (constant,
so synthesis removes them from every multiplexer) and their U<u>.tx ports are not built.
Lane count: NL, read from `localparam NL` the same way (run 4 of D-043: 2). Lanes NL-2 are absent in the
same way: L<k>.O0/O1 tied off in the top, L<k>.I0/I1 ports not built.

Usage: python spikes/r4_floorplan/gen_fabric.py [--check]
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
import tripwire_spec as S  # noqa: E402

PROD = [f"U{u}.rx" for u in range(6)] + [f"L{k}.O{o}" for k in range(3) for o in range(2)] + ["HOST_IN"]
CONS = [f"L{k}.I{i}" for k in range(3) for i in range(2)] + [f"U{u}.tx" for u in range(6)] + ["HOST_OUT"]
OUT = pathlib.Path(__file__).resolve().parent / "overlay" / "src" / "r4_fabric.v"
TOP = OUT.with_name("tt_um_tripwire.v")
NU = int(re.search(r"localparam\s+NU\s*=\s*(\d+)\s*;", TOP.read_text()).group(1))
NL = int(re.search(r"localparam\s+NL\s*=\s*(\d+)\s*;", TOP.read_text()).group(1))
assert 1 <= NU <= 6 and 1 <= NL <= 3
ABSENT = {f"U{u}.tx" for u in range(NU, 6)} | {f"L{k}.I{i}" for k in range(NL, 3) for i in range(2)}


def generate():
    np_, nc = len(PROD), len(CONS)
    assert set(S.LEGAL_SOURCES) == set(CONS), "consumer list differs from the spec"
    L = ["// GENERATED by spikes/r4_floorplan/gen_fabric.py from tools/tripwire_spec.py (LEGAL_SOURCES).",
         "// R4 spike (branch spike/r4-floorplan only): the fabric's ports, legal-source multiplexers and",
         "// release terms (ARCHITECTURE.md §4, §4.6). The producer registers live with their owners.",
         "// Producers: " + ", ".join(f"{i} {p}" for i, p in enumerate(PROD)),
         "// Consumers: " + ", ".join(f"{i} {c}" for i, c in enumerate(CONS)),
         f"// Units: {NU}, lanes: {NL} (from tt_um_tripwire.v); absent ports: " + (", ".join(sorted(ABSENT)) or "none"),
         "`default_nettype none", "",
         "module r4_fabric (",
         "    input  wire             clk,",
         "    input  wire             rst_n,",
         f"    input  wire [{np_ - 1}:0]      p_valid,",
         f"    input  wire [{np_ - 1}:0]      p_seq,",
         f"    input  wire [{np_ - 1}:0]      p_load,",
         f"    input  wire [{18 * np_ - 1}:0]    p_tok,",
         f"    input  wire [{10 * nc - 1}:0]    port_cfg,   // per consumer {{accept, sel, tap, en}}",
         f"    input  wire [{nc - 1}:0]      port_wr,",
         f"    input  wire [{nc - 1}:0]      take,",
         f"    output wire [{nc - 1}:0]      avail,",
         f"    output wire [{18 * nc - 1}:0]    head,",
         f"    output wire [{np_ - 1}:0]      all_taken,",
         f"    output wire [{8 * nc - 1}:0]    dropped",
         ");",
         f"    wire [{nc - 1}:0] blk, lseq;",
         f"    wire [{4 * nc - 1}:0] sel;", ""]
    users = {p: [] for p in range(np_)}
    for c, name in enumerate(CONS):
        if name in ABSENT:
            L += [f"    // {name}: absent (units = {NU}, lanes = {NL})",
                  f"    assign avail[{c}] = 1'b0;",
                  f"    assign head[{18 * c + 17}:{18 * c}] = 18'd0;",
                  f"    assign blk[{c}] = 1'b0;",
                  f"    assign sel[{4 * c + 3}:{4 * c}] = 4'd0;",
                  f"    assign lseq[{c}] = 1'b0;",
                  f"    assign dropped[{8 * c + 7}:{8 * c}] = 8'd0;",
                  f"    wire _unused_c{c} = &{{1'b0, port_cfg[{10 * c + 9}:{10 * c}], port_wr[{c}], take[{c}],"
                  f" blk[{c}], lseq[{c}], sel[{4 * c + 3}:{4 * c}]}};", ""]
            continue
        srcs = [PROD.index(s) for s in S.LEGAL_SOURCES[name]]
        n = len(srcs)
        for idx, p in enumerate(srcs):
            users[p].append((c, idx))
        cat = lambda sig, w: "{" + ", ".join(f"{sig}[{w * p + w - 1}:{w * p}]" if w > 1 else f"{sig}[{p}]"
                                               for p in reversed(srcs)) + "}"
        L += [f"    // {name}: " + ", ".join(f"{i} {PROD[p]}" for i, p in enumerate(srcs)),
              f"    r4_port #(.N({n})) u_c{c} (",
              "        .clk (clk), .rst_n (rst_n),",
              f"        .cfg (port_cfg[{10 * c + 9}:{10 * c}]), .cfg_wr (port_wr[{c}]),",
              f"        .src_valid ({cat('p_valid', 1)}),",
              f"        .src_seq ({cat('p_seq', 1)}),",
              f"        .src_load ({cat('p_load', 1)}),",
              f"        .src_tok ({cat('p_tok', 18)}),",
              f"        .take (take[{c}]), .avail (avail[{c}]), .head (head[{18 * c + 17}:{18 * c}]),",
              f"        .blocking (blk[{c}]), .sel (sel[{4 * c + 3}:{4 * c}]), .last_seq (lseq[{c}]),",
              f"        .dropped (dropped[{8 * c + 7}:{8 * c}])",
              "    );", ""]
    for p in range(np_):
        terms = [f"(!blk[{c}] || (sel[{4 * c + 3}:{4 * c}] != 4'd{i}) || (lseq[{c}] == p_seq[{p}]))"
                 for c, i in users[p]]
        L += [f"    // {PROD[p]}: subscribers " + ", ".join(f"{CONS[c]} (sel {i})" for c, i in users[p]),
              f"    assign all_taken[{p}] = " + ("\n        && ".join(terms) if terms else "1'b1") + ";"]
    L += ["endmodule", ""]
    return "\n".join(L)


if __name__ == "__main__":
    text = generate()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == text
        print("gen_fabric: up to date" if ok else "gen_fabric: r4_fabric.v is out of date")
        sys.exit(0 if ok else 1)
    OUT.write_text(text)
    print(f"gen_fabric: wrote {OUT.relative_to(ROOT)}")
