#!/usr/bin/env bash
# Stitch a FABulous fabric defined in arch/<NAME>/fabric.csv into one macro on IHP CMOS5L with
# LibreLane's FABulousFabric flow (phase 1: warp_tiny, 2 x LUT4x8_ha; phase 2: warp_g0). The tiles
# must be hardened first with spikes/tile_cmos5l/run.sh <TILE> (patched library in build/tile_cmos5l/).
#
# Usage: [FABRIC=warp_g0] spikes/fabric_tiny/run.sh [--tiles]   (default FABRIC=warp_tiny)
#        --tiles: harden every tile type first
# Output: build/fabric_<NAME>/, exported to macro/<NAME>/ (GDS, LEF, netlists, RTL, tool files)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$ROOT/spikes/fabric_tiny"
LIB="$ROOT/build/tile_cmos5l/fabulous-tiles"
NAME="${FABRIC:-warp_tiny}"
W="$ROOT/build/fabric_$NAME"
export PDK=ihp-sg13cmos5l
export PDK_ROOT="${PDK_ROOT:-$HOME/.cache/warp/pdk-full}"
# shellcheck disable=SC1091
. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

ARCH="$ROOT/arch/$NAME"
TILES=$(sed -n 's#^Tile,TILES/\([^/]*\)/.*#\1#p' "$ARCH/fabric.csv")
if [ "${1:-}" = "--tiles" ]; then
  for t in $TILES; do
    echo "=== tile $t"
    timeout 1500 "$ROOT/spikes/tile_cmos5l/run.sh" "$t" >/dev/null || { echo "tile $t failed"; exit 1; }
  done
fi

rm -rf "$W"
mkdir -p "$W"
ln -s "$LIB" "$W/fabulous-tiles"
sed 's#TILES/#fabulous-tiles/tiles/tiny/#' "$ARCH/fabric.csv" > "$W/$NAME.csv"
sed "s/^DESIGN_NAME: warp_tiny/DESIGN_NAME: $NAME/; s/dir::warp_tiny.csv/dir::$NAME.csv/" \
  "$HERE/config.yaml" > "$W/config.yaml"

cd "$LIB"
nix develop --accept-flake-config --command bash -c \
  "cd '$W' && librelane --pdk $PDK --pdk-root '$PDK_ROOT' --manual-pdk config.yaml --save-views-to '$W/macro'" \
  > "$W/fabric.log" 2>&1 || { tail -30 "$W/fabric.log"; exit 1; }

# LEF abstract with OpenROAD (Magic is skipped, docs/BUGS.md #2); drop unused VIA definitions.
ODB=$(ls "$W"/macro/odb/*.odb)
cat > "$W/write_lef.tcl" <<EOF
read_db {$ODB}
write_abstract_lef -bloat_occupied_layers {$W/macro/lef/$NAME.lef}
EOF
mkdir -p "$W/macro/lef"
nix develop --accept-flake-config --command openroad -exit -no_splash "$W/write_lef.tcl" > "$W/lef.log" 2>&1
python3 - "$W/macro/lef/$NAME.lef" <<'EOF'
import re, sys
p = sys.argv[1]
lines = open(p).read().split("\n")
used = {m.group(1) for l in lines for m in [re.match(r"^\s+VIA\s+\S+\s+\S+\s+(\S+)", l)] if m}
out, skip = [], None
for l in lines:
    m = re.match(r"^VIA\s+(\S+)", l)
    if skip is None and m and m.group(1) not in used:
        skip = m.group(1); continue
    if skip is not None:
        if l.strip() == f"END {skip}": skip = None
        continue
    out.append(l)
open(p, "w").write("\n".join(out))
EOF
# Placement boundary (IHP 189/4) over the whole macro, from the LEF size
read -r MW MH < <(sed -n 's/^ *SIZE \([0-9.]*\) BY \([0-9.]*\) ;/\1 \2/p' "$W/macro/lef/$NAME.lef" | head -1)
nix develop --accept-flake-config --command klayout -b -r "$HERE/add_prboundary.py" \
  -rd gds="$W/macro/gds/$NAME.gds" -rd out="$W/macro/gds/$NAME.gds" -rd w="$MW" -rd h="$MH" 2>/dev/null

# Export the macro views the chip flow uses into the repo (macro/<NAME>/)
OUT="$ROOT/macro/$NAME"
mkdir -p "$OUT"
cp "$W/macro/gds/$NAME.gds" "$W/macro/lef/$NAME.lef" "$OUT/"
cp "$W"/macro/nl/$NAME.nl.v "$OUT/$NAME.nl.v"
cp "$W/macro/fabulous/$NAME.v" "$OUT/$NAME.v"              # RTL of the fabric (simulation)
cp "$W/macro/fabulous/bitStreamSpec.csv" "$OUT/"
# tool files for the compile flow (tools/compile): nextpnr model and bitstream spec
mkdir -p "$OUT/fabulous/.FABulous"
cp "$W/macro/fabulous/bitStreamSpec.bin" "$OUT/fabulous/"
cp "$W"/macro/fabulous/.FABulous/*.txt "$OUT/fabulous/.FABulous/"
# RTL of the tiles (generated by FABulous in the tile build; for the fabric simulation)
mkdir -p "$OUT/rtl"
for t in $TILES; do cp "$LIB/tiles/tiny/$t/"*.v "$OUT/rtl/"; done
# gate-level netlists of the tiles the fabric netlist instantiates (for LVS and gate-level sim)
mkdir -p "$OUT/tiles"
for t in $TILES; do
  cp "$LIB/tiles/tiny/$t/macro/ihp-sg13cmos5l/nl/$t.nl.v" "$OUT/tiles/"
done
echo "fabric macro: $OUT ($MW x $MH um)"
