FROM ghcr.io/librelane/librelane:3.1.0.dev3
COPY --chmod=755 openroad_hotspot_wrapper.sh /usr/local/bin/tripwire-openroad-hotspot
COPY --chmod=755 openroad_banked_hold_wrapper.sh /usr/local/bin/tripwire-openroad-banked-hold
COPY banked_sram_addr_hold.tcl /usr/local/share/tripwire/banked_sram_addr_hold.tcl
ENV _LLN_OVERRIDE_OPENROAD=/usr/local/bin/tripwire-openroad-banked-hold
