#!/usr/bin/env python3
"""Generate src/<fabric>.v: the port-only black box of a hardened fabric macro (D-019), from the
ports of its generated RTL (macro/<fabric>/<fabric>.v), so the two cannot drift apart; and
test/fabric_stub.v: the same module as an idle fabric for the black-box test mode (every output
0, like a fabric whose design drives nothing), so the shell's host channel sees defined values.

Usage: scripts/gen_macro_stub.py [fabric]     (default: arch/CURRENT)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
name = sys.argv[1] if len(sys.argv) > 1 else (ROOT / "arch/CURRENT").read_text().strip()
rtl = (ROOT / "macro" / name / f"{name}.v").read_text()
m = re.search(rf"module\s+{name}\s*(#\s*\((.*?)\))?\s*\((.*?)\);", rtl, re.S)
params = {k: int(v) for k, v in re.findall(r"parameter\s+(?:integer\s+)?(\w+)\s*=\s*(\d+)", m.group(2) or "")}
ports = []
for line in m.group(3).splitlines():
    line = re.sub(r"//.*", "", line).strip().rstrip(",")
    pm = re.match(r"(input|output|inout)\s+(?:wire\s+)?(\[[^\]]*\])?\s*(\w+)$", line)
    if not pm:
        continue
    d, rng, pname = pm.groups()
    if rng:                                   # resolve parameter expressions to numbers
        expr = rng[1:-1]
        for k, v in params.items():
            expr = re.sub(rf"\b{k}\b", str(v), expr)
        hi, lo = (int(eval(e, {"__builtins__": {}})) for e in expr.split(":"))
        rng = f"[{hi}:{lo}]"
    ports.append((d, rng or "", pname))
out = [f"// Generated by scripts/gen_macro_stub.py from macro/{name}/{name}.v; do not edit.",
       f"// Black-box view of the hardened fabric macro `{name}` (built by spikes/fabric_tiny/run.sh).",
       "// Synthesis keeps it as a macro instance; LibreLane places the GDS/LEF from src/config.json",
       f"// MACROS. Simulation uses macro/{name}/{name}.v (RTL) or {name}.nl.v (gate level) instead.",
       "`default_nettype none", "", "(* blackbox *)", f"module {name} (",
       "`ifdef USE_POWER_PINS", "    inout  wire VPWR,", "    inout  wire VGND,", "`endif"]
decl = [f"    {d:<6} wire {r + ' ' if r else ''}{p}" for d, r, p in ports]
out += [d + ("," if i < len(decl) - 1 else "") for i, d in enumerate(decl)]
out += [");", "endmodule", ""]
(ROOT / "src" / f"{name}.v").write_text("\n".join(out))
print(f"src/{name}.v: {len(ports)} ports")

sim = [f"// Generated by scripts/gen_macro_stub.py from macro/{name}/{name}.v; do not edit.",
       f"// Idle model of the fabric macro `{name}` for the black-box test mode (test/Makefile):",
       "// every output 0, as a fabric whose design drives nothing. Not used for synthesis.",
       "`default_nettype none", "", f"module {name} ("]
sim += [d + ("," if i < len(decl) - 1 else "") for i, d in enumerate(decl)]
sim += [");"]
sim += [f"    assign {p} = {int(r[1:].split(':')[0]) + 1 if r else 1}'d0;" for d, r, p in ports if d == "output"]
ins = [p for d, r, p in ports if d == "input"]
sim += [f"    wire _unused = &{{{', '.join(ins)}, 1'b0}};", "endmodule", ""]
(ROOT / "test" / "fabric_stub.v").write_text("\n".join(sim))
print("test/fabric_stub.v: idle model")
