#!/usr/bin/env python3
"""Generate test/fabric_settle_gl.vh and test/fabric_settle_rtl.vh (D-023).

In 4-state zero-delay simulation the fabric's unused routing is a problem silicon does not have.
Unused wires sit on default mux inputs and form combinational loops across tiles:
  - a loop that starts at X stays X, and gate-level LUTs pass X on from inputs the configured
    function ignores (silicon: the loop holds some definite 0/1, the LUT ignores it);
  - a half-written configuration (while loading one design over another) can close a loop that
    oscillates; silicon rings until the load completes, with the design in reset and every pin
    parked, but a zero-delay simulator never advances past it unless the loop is X.
So the testbench forces every inter-tile routing wire for 1 ns and releases it: to X when
tb.unsettle_routing rises (before a load) and to 0 when tb.settle_routing rises (after a load,
mux selects known, design in reset). Used routing is re-driven by its source at once; the
configuration chain (FrameData/FrameStrobe) is untouched.

Usage: scripts/gen_fabric_settle.py     (reads macro/warp_tiny/warp_tiny.{nl.v,v})
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MACRO = ROOT / "macro/warp_tiny"
HIER = "user_project.u_fabric"


def wires_gl():
    text = (MACRO / "warp_tiny.nl.v").read_text()
    return [f"\\{m.group(1)} " for m in re.finditer(
        r"^\s*wire\s+\\?(Tile_X\d+Y\d+_\w+(?:\[\d+\])?)\s*;", text, re.M)]


def wires_rtl():
    text = (MACRO / "warp_tiny.v").read_text()
    return [m.group(1) for m in re.finditer(
        r"^\s*wire\s*(?:\[[^\]]*\])?\s*(Tile_X\d+Y\d+_\w+)\s*;", text, re.M)]


def emit(path, source, wires):
    wires = [w for w in wires if "FrameData" not in w and "FrameStrobe" not in w]
    if not wires:
        raise SystemExit(f"no inter-tile wires found in {source}")
    out = [f"// Generated by scripts/gen_fabric_settle.py from {source}; do not edit.",
           f"// {len(wires)} inter-tile routing wires (D-023)."]
    for trig, val in (("settle_routing", "1'b0"), ("unsettle_routing", "'bx")):
        out += [f"always @(posedge {trig}) begin"]
        out += [f"  force {HIER}.{w} = {val};" for w in wires]
        out += ["  #1;"]
        out += [f"  release {HIER}.{w};" for w in wires]
        out += ["end"]
    path.write_text("\n".join(out) + "\n")
    print(f"{path.relative_to(ROOT)}: {len(wires)} wires")


emit(ROOT / "test/fabric_settle_gl.vh", "macro/warp_tiny/warp_tiny.nl.v", wires_gl())
emit(ROOT / "test/fabric_settle_rtl.vh", "macro/warp_tiny/warp_tiny.v", wires_rtl())
