#!/usr/bin/env python3
"""Generate macro/<fabric>/fabulous/.FABulous/placement_estimate.txt: timing arcs for the WARP hard
primitives (wp_timer, wp_shift) that nextpnr's FABulous back end reads (nextpnr >= 0.11,
docs/VERSIONS.md), from tools/timing/prims.arcs (tools/timing/prim_sta.sh: OpenSTA of each
primitive synthesized alone, slow corner). Without it nextpnr leaves every path through a
primitive untimed (BUGS #17). The tile library's own cells keep nextpnr's built-in arcs.

Arcs are multiplied by MARGIN: the standalone synthesis has no placement or wiring inside the
tile (tools/timing/README.md). Negative hold times are written as 0.

Usage: scripts/gen_prim_timing.py [fabric]     (default: arch/CURRENT)
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

MARGIN = 1.5
ROOT = Path(__file__).resolve().parents[1]
fabric = sys.argv[1] if len(sys.argv) > 1 else (ROOT / "arch/CURRENT").read_text().strip()
arcs = defaultdict(list)
for line in (ROOT / "tools/timing/prims.arcs").read_text().splitlines():
    f = line.split()
    arcs[f[0]].append(f[1:])


def port(name):
    """Bus bit d[3] is the BEL pin d3 (bel.v2.txt)."""
    return re.sub(r"\[(\d+)\]$", r"\1", name)


out = ["# Generated by scripts/gen_prim_timing.py from tools/timing/prims.arcs; do not edit.",
       f"# WARP hard primitive timing arcs (ns, slow corner, x{MARGIN} margin), BUGS #17."]
for bel, rows in arcs.items():
    setup = {port(r[1]): float(r[2]) for r in rows if r[0] == "setup"}
    hold = {port(r[1]): float(r[2]) for r in rows if r[0] == "hold"}
    out += [f"BelBegin,{bel}", "Clock,CLK,"]
    for p, s in setup.items():
        out.append(f"SetupHold,{p},CLK,{s * MARGIN:.3f},{max(hold.get(p, 0.0), 0.0) * MARGIN:.3f},")
    for r in rows:
        if r[0] == "clk2out":
            out.append(f"ClkToOut,{port(r[1])},CLK,{float(r[2]) * MARGIN:.3f},")
        elif r[0] == "comb":
            out.append(f"Delay,{port(r[1])},{port(r[2])},{float(r[3]) * MARGIN:.3f},")
    out.append("BelEnd")
dst = ROOT / "macro" / fabric / "fabulous" / ".FABulous" / "placement_estimate.txt"
dst.write_text("\n".join(out) + "\n")
print(f"{dst.relative_to(ROOT)}: {sum(len(v) for v in arcs.values())} arcs for {', '.join(arcs)}")
