#!/usr/bin/env python3
"""Generate the G1 primitive tile (D-026) from the LUT4x8_ha tile of the pinned tile library.

The primitive tile takes one LUT-tile slot: same routing base (Base.csv/Base.list), same global
clock, carry passed straight through, and in place of the 8 LCs: 2 x wp_timer (TA_, TB_) and
2 x wp_shift (SA_, SB_) (arch/prims). Its switch matrix is the LUT tile's with the block ports
substituted:
  - the 32 LUT inputs (L{A..H}_I{0..3}) become the 32 block inputs, with the same routing;
  - the 8 LUT outputs' slots in the 32 output muxes (JN/JE/JS/JW2BEG0..7) are shared by the 22
    block outputs, rotating so each output appears ~10 times and no mux gets the same one twice;
  - LC carry/SR/EN connections are dropped; CO is driven from CI (carry passes through).

Usage: scripts/gen_prim_tile.py <tile library dir> <output dir>
Writes <out>/PRIM2T2S.csv and <out>/PRIM2T2S_switch_matrix.list.
"""
import re
import sys
from pathlib import Path

NAME = "PRIM2T2S"
lib, out = Path(sys.argv[1]), Path(sys.argv[2])
src = lib / "tiles/tiny/LUT4x8_ha"

INPUTS = {  # LUT input -> block input
    **{f"LA_I{k}": f"TA_{p}" for k, p in enumerate(("rst", "load", "half", "en"))},
    **{f"LB_I{k}": f"TB_{p}" for k, p in enumerate(("rst", "load", "half", "en"))},
    **{f"LC_I{k}": f"SA_{p}" for k, p in enumerate(("rst", "load", "step", "sin"))},
    **{f"LD_I{k}": f"SA_d{k}" for k in range(4)},
    **{f"LE_I{k}": f"SA_d{4 + k}" for k in range(4)},
    **{f"LF_I{k}": f"SB_{p}" for k, p in enumerate(("rst", "load", "step", "sin"))},
    **{f"LG_I{k}": f"SB_d{k}" for k in range(4)},
    **{f"LH_I{k}": f"SB_d{4 + k}" for k in range(4)},
}
OUTPUTS = (["TA_tc", "TB_tc", "SA_sout", "SA_done", "SB_sout", "SB_done"]
           + [f"SA_q{i}" for i in range(8)] + [f"SB_q{i}" for i in range(8)])
CLOCKS = {"LA_CLK": "TA_CLK", "LB_CLK": "TB_CLK", "LC_CLK": "SA_CLK", "LD_CLK": "SB_CLK"}
LUT_O = [f"L{c}_O" for c in "ABCDEFGH"]


def expand(line):
    """FABulous list syntax: 'A[x|y],[p|q]' / 'A,B' -> [(dst, src), ...]."""
    dst, srcs = [p.strip() for p in line.split(",", 1)]

    def alts(s):
        m = re.fullmatch(r"(.*?)\[([^\]]*)\](.*)", s)
        if not m:
            return [s]
        return [m.group(1) + a + m.group(3) for a in m.group(2).split("|")]
    d, s = alts(dst), alts(srcs)
    if len(d) == 1:
        d = d * len(s)
    if len(s) == 1:
        s = s * len(d)
    return list(zip(d, s))


pairs, out_rows = [], {}
for raw in (src / "LUT4x8_ha_switch_matrix.list").read_text().splitlines():
    line = raw.split("#", 1)[0].strip()
    if not line:
        continue
    if line.upper().startswith("INCLUDE"):
        pairs.append(("INCLUDE", line.split(",", 1)[1].strip()))
        continue
    for dst, s in expand(line):
        if re.search(r"L[A-H]_(Ci|Co|SR|EN)$", dst) or re.search(r"L[A-H]_(Ci|Co)$", s):
            continue
        if re.match(r"(GSR|GEN|J_SR|J_EN)_", dst) or re.match(r"(GSR|GEN|J_SR|J_EN)_", s):
            continue                                    # the LCs' shared set/reset and enable
        if dst in INPUTS:
            dst = INPUTS[dst]
        if dst in CLOCKS or re.fullmatch(r"L[A-H]_CLK", dst):
            if dst not in CLOCKS:
                continue
            dst = CLOCKS[dst]
        if s in LUT_O:
            out_rows.setdefault(dst, []).append(len(pairs))
        pairs.append((dst, s))

# share the LUT-output slots of each output mux among the 22 block outputs
rows = sorted(out_rows)
for r, dst in enumerate(rows):
    for i, idx in enumerate(out_rows[dst]):
        pairs[idx] = (dst, OUTPUTS[(r * 7 + i) % len(OUTPUTS)])
pairs.append(("CO0", "CI0"))                            # carry passes through
seen, lines = set(), [f"# {NAME}: generated by scripts/gen_prim_tile.py from LUT4x8_ha; do not edit."]
for dst, s in pairs:
    if dst == "INCLUDE":
        lines.append(f"INCLUDE, {s}")
    elif (dst, s) not in seen:
        seen.add((dst, s))
        lines.append(f"{dst},{s}")
out.mkdir(parents=True, exist_ok=True)
(out / f"{NAME}_switch_matrix.list").write_text("\n".join(lines) + "\n")

csv = (src / "LUT4x8_ha.csv").read_text()
csv = csv.replace("TILE,LUT4x8_ha,", f"TILE,{NAME},")
csv = re.sub(r"^JUMP,(GSR|GEN|J_SR|J_EN)_BEG.*\n", "", csv, flags=re.M)
bels = "".join(f"BEL,../../../primitives/WARP/fabulous/{m}.v,{p},,,,\n"
               for m, p in (("wp_timer", "TA_"), ("wp_timer", "TB_"), ("wp_shift", "SA_"), ("wp_shift", "SB_")))
csv = re.sub(r"(^BEL,.*\n)+", bels, csv, flags=re.M)
csv = csv.replace("MATRIX,./LUT4x8_ha_switch_matrix.list", f"MATRIX,./{NAME}_switch_matrix.list")
(out / f"{NAME}.csv").write_text(csv)

used = {s for _, s in pairs} | {d for d, _ in pairs}
missing = [p for p in list(INPUTS.values()) + OUTPUTS + list(CLOCKS.values()) if p not in used]
counts = {o: sum(1 for _, s in pairs if s == o) for o in OUTPUTS}
print(f"{NAME}: {len(lines) - 1} switch-matrix entries; outputs reach {min(counts.values())}"
      f"-{max(counts.values())} muxes each; unconnected block ports: {missing or 'none'}")
