"""GENERATED by tools/gen/gen.py from spec/tripwire.yaml. DO NOT EDIT."""

VERSION = '1.1'
STATUS = 'frozen'

DATA_BITS = 16
TAG_BITS = 2
TAGS = {'DATA': 0, 'CTRL': 1, 'EVENT': 2, 'ERR': 3}

OPS = {'MOV': 0, 'ADD': 1, 'SUB': 2, 'AND': 3, 'OR': 4, 'XOR': 5, 'SHL': 6, 'SHR': 7, 'SHOR': 8, 'EXT': 9, 'CMPM': 10, 'LTU': 11, 'PAR': 12, 'MKCTL': 13, 'CALL': 14, 'MOVB': 15}

SLOT_BITS = 53
SLOT_HOST_WORDS = 4
SLOT_FIELDS = {  # name: (lsb, width)
    'V': (0, 1),
    'U': (1, 1),
    'SE': (2, 1),
    'SV': (3, 4),
    'FM': (7, 4),
    'FV': (11, 4),
    'TE': (15, 1),
    'TAG': (16, 2),
    'HE': (18, 1),
    'HV': (19, 1),
    'OP': (20, 4),
    'DST': (24, 3),
    'ASRC': (27, 3),
    'DQ': (30, 1),
    'BSEL': (31, 2),
    'IMM': (33, 8),
    'NSE': (41, 1),
    'NS': (42, 4),
    'DFE': (46, 1),
    'DF': (47, 2),
    'OT': (49, 2),
    'KT': (51, 1),
    'HS': (52, 1),
}
DST = {'r0': 0, 'r1': 1, 'r2': 2, 'r3': 3, 'O0': 4, 'O1': 5, 'none': 6}
ASRC = {'r0': 0, 'r1': 1, 'r2': 2, 'r3': 3, 'I0': 4, 'I1': 5, 'zero': 6, 'time': 7}
BSEL = {'reg': 0, 'imm': 1, 'k': 2}

ROUTINE_BITS = 16
ROUTINE_ALU_SELECT = 0
ROUTINE_ALU_FIELDS = {'op': (14, 11), 'rd': (10, 9), 'ra': (8, 7), 'bs': (6, 6), 'b': (5, 0)}  # name: (msb, lsb)
ROUTINE_CTRL_SELECT = 1
ROUTINE_CTRL_SUB = (14, 12)
ROUTINE_CTRL = {  # name: (sub code, {field: (msb, lsb)})
    'LDI': (0, {'rd': (11, 10), 'imm': (9, 0)}),
    'LDIH': (1, {'rd': (11, 10), 'imm': (9, 0)}),
    'BR': (2, {'cond': (11, 9), 'off': (8, 0)}),
    'DJNZ': (3, {'rd': (11, 10), 'off': (9, 0)}),
    'LD': (4, {'rd': (11, 10), 'ra': (9, 8), 'off': (7, 0)}),
    'ST': (5, {'rd': (11, 10), 'ra': (9, 8), 'off': (7, 0)}),
    'OUT': (6, {'port': (11, 11), 'tag': (10, 9), 'ra': (8, 7)}),
    'SYS': (7, {'fn': (11, 8), 'arg': (7, 0)}),
}
ROUTINE_SIGNED = {'LDI': (), 'LDIH': (), 'BR': ('off',), 'DJNZ': ('off',), 'LD': (), 'ST': (), 'OUT': (), 'SYS': ()}
BR_COND = {'always': 0, 'rz': 1, 'nrz': 2}
SYS = {'NOP': 0, 'RET': 1, 'SETST': 2, 'SETF': 3, 'CLRF': 4, 'TSTF': 5, 'CPYF': 6, 'GETT': 7, 'GETK': 8}

PIN_CMD = {'LEVEL': 1, 'OE': 2, 'CLK': 3, 'GAP': 4, 'SYNC': 5, 'SETN': 6, 'WAIT': 7, 'SAMPLE': 8, 'FRAME': 9, 'LINE': 10, 'JAM': 11}
TX_LENTOK = {'len': (15, 12), 'payload': (11, 0)}

PAD_GROUPS = {'ui': (0, 8, 'in'), 'uo': (8, 8, 'out'), 'uio': (16, 8, 'inout')}
PADS = {'ui0': 0, 'ui1': 1, 'ui2': 2, 'ui3': 3, 'ui4': 4, 'ui5': 5, 'ui6': 6, 'ui7': 7, 'uo0': 8, 'uo1': 9, 'uo2': 10, 'uo3': 11, 'uo4': 12, 'uo5': 13, 'uo6': 14, 'uo7': 15, 'uio0': 16, 'uio1': 17, 'uio2': 18, 'uio3': 19, 'uio4': 20, 'uio5': 21, 'uio6': 22, 'uio7': 23}
HOST_PADS = (4, 5, 6, 11, 14)

FABRIC_SEL_BITS = 4
LEGAL_SOURCES = {  # consumer port: sources in sel order (ARCHITECTURE.md §4.6)
    'L0.I0': ('U0.rx', 'U1.rx', 'U2.rx', 'U3.rx', 'U4.rx', 'U5.rx', 'HOST_IN', 'L2.O1'),
    'L1.I0': ('U0.rx', 'U1.rx', 'U2.rx', 'U3.rx', 'U4.rx', 'U5.rx', 'HOST_IN', 'L0.O1'),
    'L2.I0': ('U0.rx', 'U1.rx', 'U2.rx', 'U3.rx', 'U4.rx', 'U5.rx', 'HOST_IN', 'L1.O1'),
    'L0.I1': ('U0.rx', 'U1.rx', 'U2.rx', 'U3.rx', 'U4.rx', 'U5.rx', 'HOST_IN', 'L1.O0', 'L2.O1'),
    'L1.I1': ('U0.rx', 'U1.rx', 'U2.rx', 'U3.rx', 'U4.rx', 'U5.rx', 'HOST_IN', 'L2.O0', 'L0.O1'),
    'L2.I1': ('U0.rx', 'U1.rx', 'U2.rx', 'U3.rx', 'U4.rx', 'U5.rx', 'HOST_IN', 'L0.O0', 'L1.O1'),
    'U0.tx': ('L0.O0', 'L1.O0', 'L2.O0', 'L0.O1', 'L1.O1', 'L2.O1', 'HOST_IN'),
    'U1.tx': ('L0.O0', 'L1.O0', 'L2.O0', 'L0.O1', 'L1.O1', 'L2.O1', 'HOST_IN'),
    'U2.tx': ('L0.O0', 'L1.O0', 'L2.O0', 'L0.O1', 'L1.O1', 'L2.O1', 'HOST_IN'),
    'U3.tx': ('L0.O0', 'L1.O0', 'L2.O0', 'L0.O1', 'L1.O1', 'L2.O1', 'HOST_IN'),
    'U4.tx': ('L0.O0', 'L1.O0', 'L2.O0', 'L0.O1', 'L1.O1', 'L2.O1', 'HOST_IN'),
    'U5.tx': ('L0.O0', 'L1.O0', 'L2.O0', 'L0.O1', 'L1.O1', 'L2.O1', 'HOST_IN'),
    'HOST_OUT': ('L0.O0', 'L1.O0', 'L2.O0', 'L0.O1', 'L1.O1', 'L2.O1', 'U0.rx', 'U1.rx'),
}

PIN_CFG_BASE = 0x3000
PIN_CFG_STRIDE = 32
PIN_OWNER_BASE = 0x30c0
PIN_CFG_FIELDS = {  # name: (bit, width, kind) inside a unit's block (ARCHITECTURE.md §7.2)
    'txmode': (0, 3, 'enum'),
    'rxmode': (3, 2, 'enum'),
    'order': (5, 1, 'enum'),
    'od': (6, 1, 'bool'),
    'idle': (7, 1, 'uint'),
    'autorearm': (8, 1, 'bool'),
    'rx_echo': (9, 1, 'bool'),
    'tx_lentok': (10, 1, 'bool'),
    'tx_preload': (11, 1, 'bool'),
    'stretch': (12, 1, 'bool'),
    'nrzi': (13, 1, 'bool'),
    'oe_auto': (14, 1, 'bool'),
    'pin_a': (16, 5, 'pad'),
    'pin_b': (21, 5, 'pad'),
    'rx_edge': (26, 1, 'enum'),
    'tx_edge': (27, 2, 'enum'),
    'pin_c': (32, 5, 'pad'),
    'c_active': (37, 1, 'uint'),
    'c_oe': (38, 1, 'bool'),
    'pin_s': (39, 5, 'pad'),
    'pin_n': (48, 5, 'pad'),
    'ev_pin': (53, 1, 'enum'),
    'ev_edge': (54, 2, 'enum'),
    'ev_qual': (56, 2, 'enum'),
    'ev_reset': (58, 1, 'bool'),
    'period': (64, 24, 'q8'),
    'presc': (88, 8, 'm1'),
    'sampleofs': (96, 24, 'sofs'),
    'nbits': (120, 4, 'm1'),
    'rx_nbits': (128, 5, 'uint'),
    'rx_nbits2': (133, 5, 'uint'),
    'sym0_t1': (144, 12, 'uint'),
    'sym0_first': (156, 1, 'uint'),
    'sym0_t2': (160, 12, 'uint'),
    'sym1_t1': (176, 12, 'uint'),
    'sym1_first': (188, 1, 'uint'),
    'sym1_t2': (192, 12, 'uint'),
    'carrier': (208, 24, 'q8'),
    'sjw': (240, 24, 'q8'),
    'idle_bits': (264, 5, 'uint'),
    'resync': (269, 1, 'enum'),
    'delim': (270, 2, 'enum'),
    'stuff_n': (272, 4, 'uint'),
    'stuff_lvl': (276, 2, 'enum'),
    'crc_width': (278, 5, 'uint'),
    'crc_skip': (283, 5, 'uint'),
    'crc_poly': (288, 16, 'uint'),
    'crc_init': (304, 16, 'uint'),
    'crc_res': (320, 16, 'uint'),
    'crc_xor': (336, 16, 'uint'),
}
PIN_CFG_ENUMS = {
    'txmode': {'level': 0, 'shift': 1, 'clkgen': 2, 'pulse': 3, 'bitsync': 4},
    'rxmode': {'off': 0, 'shift_rx': 1, 'linked_rx': 2, 'bitsync': 3},
    'order': {'lsb': 0, 'msb': 1},
    'rx_edge': {'rise': 0, 'fall': 1},
    'tx_edge': {'none': 0, 'rise': 1, 'fall': 2},
    'ev_pin': {'a': 0, 'c': 1},
    'ev_edge': {'none': 0, 'rise': 1, 'fall': 2, 'both': 3},
    'ev_qual': {'none': 0, 0: 2, 1: 3},
    'resync': {'dom': 0, 'both': 1},
    'delim': {'none': 0, 'flag': 1, 'se0': 2},
    'stuff_lvl': {'none': 0, 0: 2, 1: 3},
}
PIN_CFG_STORAGE = 'latch'
PIN_CFG_READABLE = False
PIN_FEATURES = {  # optional feature: (fields, {enum field: modes}) (D-040)
    'pulse': (('sym0_t1', 'sym0_first', 'sym0_t2', 'sym1_t1', 'sym1_first', 'sym1_t2'), {'txmode': ('pulse',)}),
    'carrier': (('carrier',), {}),
    'bitsync': (('nrzi', 'oe_auto', 'sjw', 'idle_bits', 'resync', 'delim', 'stuff_n', 'stuff_lvl', 'crc_width', 'crc_skip', 'crc_poly', 'crc_init', 'crc_res', 'crc_xor'), {'txmode': ('bitsync',), 'rxmode': ('bitsync',)}),
}
PIN_UNIT_FEATURES = (  # U0, U1, ...: the optional features each unit has
    ('pulse', 'carrier', 'bitsync'),
    ('pulse', 'carrier', 'bitsync'),
    (),
    (),
    (),
    (),
)
