"""GENERATED by tools/gen/gen.py from spec/tripwire.yaml. DO NOT EDIT."""

VERSION = '0.1'
STATUS = 'draft'

DATA_BITS = 16
TAG_BITS = 2
TAGS = {'DATA': 0, 'CTRL': 1, 'EVENT': 2, 'ERR': 3}

OPS = {'MOV': 0, 'ADD': 1, 'SUB': 2, 'AND': 3, 'OR': 4, 'XOR': 5, 'SHL': 6, 'SHR': 7, 'SHOR': 8, 'EXT': 9, 'CMPM': 10, 'LTU': 11, 'PAR': 12, 'MKCTL': 13, 'CALL': 14, 'MOVB': 15}

SLOT_BITS = 53
SLOT_HOST_WORDS = 4
SLOT_FIELDS = {  # name: (lsb, width)
    'V': (0, 1),
    'U': (1, 1),
    'SE': (2, 1),
    'SV': (3, 4),
    'FM': (7, 4),
    'FV': (11, 4),
    'TE': (15, 1),
    'TAG': (16, 2),
    'HE': (18, 1),
    'HV': (19, 1),
    'OP': (20, 4),
    'DST': (24, 3),
    'ASRC': (27, 3),
    'DQ': (30, 1),
    'BSEL': (31, 2),
    'IMM': (33, 8),
    'NSE': (41, 1),
    'NS': (42, 4),
    'DFE': (46, 1),
    'DF': (47, 2),
    'OT': (49, 2),
    'KT': (51, 1),
    'HS': (52, 1),
}
DST = {'r0': 0, 'r1': 1, 'r2': 2, 'r3': 3, 'O0': 4, 'O1': 5, 'none': 6}
ASRC = {'r0': 0, 'r1': 1, 'r2': 2, 'r3': 3, 'I0': 4, 'I1': 5, 'zero': 6, 'time': 7}
BSEL = {'reg': 0, 'imm': 1, 'k': 2}

ROUTINE_BITS = 16
ROUTINE_ALU_SELECT = 0
ROUTINE_ALU_FIELDS = {'op': (14, 11), 'rd': (10, 9), 'ra': (8, 7), 'bs': (6, 6), 'b': (5, 0)}  # name: (msb, lsb)
ROUTINE_CTRL_SELECT = 1
ROUTINE_CTRL_SUB = (14, 12)
ROUTINE_CTRL = {  # name: (sub code, {field: (msb, lsb)})
    'LDI': (0, {'rd': (11, 10), 'imm': (9, 0)}),
    'LDIH': (1, {'rd': (11, 10), 'imm': (9, 0)}),
    'BR': (2, {'cond': (11, 9), 'off': (8, 0)}),
    'DJNZ': (3, {'rd': (11, 10), 'off': (9, 0)}),
    'LD': (4, {'rd': (11, 10), 'ra': (9, 8), 'off': (7, 0)}),
    'ST': (5, {'rd': (11, 10), 'ra': (9, 8), 'off': (7, 0)}),
    'OUT': (6, {'port': (11, 11), 'tag': (10, 9), 'ra': (8, 7)}),
    'SYS': (7, {'fn': (11, 8), 'arg': (7, 0)}),
}
ROUTINE_SIGNED = {'LDI': (), 'LDIH': (), 'BR': ('off',), 'DJNZ': ('off',), 'LD': (), 'ST': (), 'OUT': (), 'SYS': ()}
BR_COND = {'always': 0, 'rz': 1, 'nrz': 2}
SYS = {'NOP': 0, 'RET': 1, 'SETST': 2, 'SETF': 3, 'CLRF': 4, 'TSTF': 5, 'CPYF': 6, 'GETT': 7, 'GETK': 8}

PIN_CMD = {'LEVEL': 1, 'OE': 2, 'CLK': 3, 'GAP': 4, 'SYNC': 5, 'SETN': 6, 'WAIT': 7}
TX_LENTOK = {'len': (15, 12), 'payload': (11, 0)}

PAD_GROUPS = {'ui': (0, 8, 'in'), 'uo': (8, 8, 'out'), 'uio': (16, 8, 'inout')}
PADS = {'ui0': 0, 'ui1': 1, 'ui2': 2, 'ui3': 3, 'ui4': 4, 'ui5': 5, 'ui6': 6, 'ui7': 7, 'uo0': 8, 'uo1': 9, 'uo2': 10, 'uo3': 11, 'uo4': 12, 'uo5': 13, 'uo6': 14, 'uo7': 15, 'uio0': 16, 'uio1': 17, 'uio2': 18, 'uio3': 19, 'uio4': 20, 'uio5': 21, 'uio6': 22, 'uio7': 23}
HOST_PADS = (4, 5, 6, 14, 15)
