// GENERATED by spikes/r4_floorplan/gen_fabric.py from tools/tripwire_spec.py (LEGAL_SOURCES).
// R4 spike (branch spike/r4-floorplan only): the fabric's ports, legal-source multiplexers and
// release terms (ARCHITECTURE.md §4, §4.6). The producer registers live with their owners.
// Producers: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 L0.O0, 7 L0.O1, 8 L1.O0, 9 L1.O1, 10 L2.O0, 11 L2.O1, 12 HOST_IN
// Consumers: 0 L0.I0, 1 L0.I1, 2 L1.I0, 3 L1.I1, 4 L2.I0, 5 L2.I1, 6 U0.tx, 7 U1.tx, 8 U2.tx, 9 U3.tx, 10 U4.tx, 11 U5.tx, 12 HOST_OUT
`default_nettype none

module r4_fabric (
    input  wire             clk,
    input  wire             rst_n,
    input  wire [12:0]      p_valid,
    input  wire [12:0]      p_seq,
    input  wire [12:0]      p_load,
    input  wire [233:0]    p_tok,
    input  wire [129:0]    port_cfg,   // per consumer {accept, sel, tap, en}
    input  wire [12:0]      port_wr,
    input  wire [12:0]      take,
    output wire [12:0]      avail,
    output wire [233:0]    head,
    output wire [12:0]      all_taken,
    output wire [103:0]    dropped
);
    wire [12:0] blk, lseq;
    wire [51:0] sel;

    // L0.I0: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L2.O1
    r4_port #(.N(8)) u_c0 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[9:0]), .cfg_wr (port_wr[0]),
        .src_valid ({p_valid[11], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[11], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[11], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[215:198], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[0]), .avail (avail[0]), .head (head[17:0]),
        .blocking (blk[0]), .sel (sel[3:0]), .last_seq (lseq[0]),
        .dropped (dropped[7:0])
    );

    // L0.I1: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L1.O0, 8 L2.O1
    r4_port #(.N(9)) u_c1 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[19:10]), .cfg_wr (port_wr[1]),
        .src_valid ({p_valid[11], p_valid[8], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[11], p_seq[8], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[11], p_load[8], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[215:198], p_tok[161:144], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[1]), .avail (avail[1]), .head (head[35:18]),
        .blocking (blk[1]), .sel (sel[7:4]), .last_seq (lseq[1]),
        .dropped (dropped[15:8])
    );

    // L1.I0: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L0.O1
    r4_port #(.N(8)) u_c2 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[29:20]), .cfg_wr (port_wr[2]),
        .src_valid ({p_valid[7], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[7], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[7], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[143:126], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[2]), .avail (avail[2]), .head (head[53:36]),
        .blocking (blk[2]), .sel (sel[11:8]), .last_seq (lseq[2]),
        .dropped (dropped[23:16])
    );

    // L1.I1: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L2.O0, 8 L0.O1
    r4_port #(.N(9)) u_c3 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[39:30]), .cfg_wr (port_wr[3]),
        .src_valid ({p_valid[7], p_valid[10], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[7], p_seq[10], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[7], p_load[10], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[143:126], p_tok[197:180], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[3]), .avail (avail[3]), .head (head[71:54]),
        .blocking (blk[3]), .sel (sel[15:12]), .last_seq (lseq[3]),
        .dropped (dropped[31:24])
    );

    // L2.I0: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L1.O1
    r4_port #(.N(8)) u_c4 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[49:40]), .cfg_wr (port_wr[4]),
        .src_valid ({p_valid[9], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[9], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[9], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[179:162], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[4]), .avail (avail[4]), .head (head[89:72]),
        .blocking (blk[4]), .sel (sel[19:16]), .last_seq (lseq[4]),
        .dropped (dropped[39:32])
    );

    // L2.I1: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L0.O0, 8 L1.O1
    r4_port #(.N(9)) u_c5 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[59:50]), .cfg_wr (port_wr[5]),
        .src_valid ({p_valid[9], p_valid[6], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[9], p_seq[6], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[9], p_load[6], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[179:162], p_tok[125:108], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[5]), .avail (avail[5]), .head (head[107:90]),
        .blocking (blk[5]), .sel (sel[23:20]), .last_seq (lseq[5]),
        .dropped (dropped[47:40])
    );

    // U0.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    r4_port #(.N(7)) u_c6 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[69:60]), .cfg_wr (port_wr[6]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[6]), .avail (avail[6]), .head (head[125:108]),
        .blocking (blk[6]), .sel (sel[27:24]), .last_seq (lseq[6]),
        .dropped (dropped[55:48])
    );

    // U1.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    r4_port #(.N(7)) u_c7 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[79:70]), .cfg_wr (port_wr[7]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[7]), .avail (avail[7]), .head (head[143:126]),
        .blocking (blk[7]), .sel (sel[31:28]), .last_seq (lseq[7]),
        .dropped (dropped[63:56])
    );

    // U2.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    r4_port #(.N(7)) u_c8 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[89:80]), .cfg_wr (port_wr[8]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[8]), .avail (avail[8]), .head (head[161:144]),
        .blocking (blk[8]), .sel (sel[35:32]), .last_seq (lseq[8]),
        .dropped (dropped[71:64])
    );

    // U3.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    r4_port #(.N(7)) u_c9 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[99:90]), .cfg_wr (port_wr[9]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[9]), .avail (avail[9]), .head (head[179:162]),
        .blocking (blk[9]), .sel (sel[39:36]), .last_seq (lseq[9]),
        .dropped (dropped[79:72])
    );

    // U4.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    r4_port #(.N(7)) u_c10 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[109:100]), .cfg_wr (port_wr[10]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[10]), .avail (avail[10]), .head (head[197:180]),
        .blocking (blk[10]), .sel (sel[43:40]), .last_seq (lseq[10]),
        .dropped (dropped[87:80])
    );

    // U5.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    r4_port #(.N(7)) u_c11 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[119:110]), .cfg_wr (port_wr[11]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[11]), .avail (avail[11]), .head (head[215:198]),
        .blocking (blk[11]), .sel (sel[47:44]), .last_seq (lseq[11]),
        .dropped (dropped[95:88])
    );

    // HOST_OUT: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 U0.rx, 7 U1.rx
    r4_port #(.N(8)) u_c12 (
        .clk (clk), .rst_n (rst_n),
        .cfg (port_cfg[129:120]), .cfg_wr (port_wr[12]),
        .src_valid ({p_valid[1], p_valid[0], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[1], p_seq[0], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[1], p_load[0], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[35:18], p_tok[17:0], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[12]), .avail (avail[12]), .head (head[233:216]),
        .blocking (blk[12]), .sel (sel[51:48]), .last_seq (lseq[12]),
        .dropped (dropped[103:96])
    );

    // U0.rx: subscribers L0.I0 (sel 0), L0.I1 (sel 0), L1.I0 (sel 0), L1.I1 (sel 0), L2.I0 (sel 0), L2.I1 (sel 0), HOST_OUT (sel 6)
    assign all_taken[0] = (!blk[0] || (sel[3:0] != 4'd0) || (lseq[0] == p_seq[0]))
        && (!blk[1] || (sel[7:4] != 4'd0) || (lseq[1] == p_seq[0]))
        && (!blk[2] || (sel[11:8] != 4'd0) || (lseq[2] == p_seq[0]))
        && (!blk[3] || (sel[15:12] != 4'd0) || (lseq[3] == p_seq[0]))
        && (!blk[4] || (sel[19:16] != 4'd0) || (lseq[4] == p_seq[0]))
        && (!blk[5] || (sel[23:20] != 4'd0) || (lseq[5] == p_seq[0]))
        && (!blk[12] || (sel[51:48] != 4'd6) || (lseq[12] == p_seq[0]));
    // U1.rx: subscribers L0.I0 (sel 1), L0.I1 (sel 1), L1.I0 (sel 1), L1.I1 (sel 1), L2.I0 (sel 1), L2.I1 (sel 1), HOST_OUT (sel 7)
    assign all_taken[1] = (!blk[0] || (sel[3:0] != 4'd1) || (lseq[0] == p_seq[1]))
        && (!blk[1] || (sel[7:4] != 4'd1) || (lseq[1] == p_seq[1]))
        && (!blk[2] || (sel[11:8] != 4'd1) || (lseq[2] == p_seq[1]))
        && (!blk[3] || (sel[15:12] != 4'd1) || (lseq[3] == p_seq[1]))
        && (!blk[4] || (sel[19:16] != 4'd1) || (lseq[4] == p_seq[1]))
        && (!blk[5] || (sel[23:20] != 4'd1) || (lseq[5] == p_seq[1]))
        && (!blk[12] || (sel[51:48] != 4'd7) || (lseq[12] == p_seq[1]));
    // U2.rx: subscribers L0.I0 (sel 2), L0.I1 (sel 2), L1.I0 (sel 2), L1.I1 (sel 2), L2.I0 (sel 2), L2.I1 (sel 2)
    assign all_taken[2] = (!blk[0] || (sel[3:0] != 4'd2) || (lseq[0] == p_seq[2]))
        && (!blk[1] || (sel[7:4] != 4'd2) || (lseq[1] == p_seq[2]))
        && (!blk[2] || (sel[11:8] != 4'd2) || (lseq[2] == p_seq[2]))
        && (!blk[3] || (sel[15:12] != 4'd2) || (lseq[3] == p_seq[2]))
        && (!blk[4] || (sel[19:16] != 4'd2) || (lseq[4] == p_seq[2]))
        && (!blk[5] || (sel[23:20] != 4'd2) || (lseq[5] == p_seq[2]));
    // U3.rx: subscribers L0.I0 (sel 3), L0.I1 (sel 3), L1.I0 (sel 3), L1.I1 (sel 3), L2.I0 (sel 3), L2.I1 (sel 3)
    assign all_taken[3] = (!blk[0] || (sel[3:0] != 4'd3) || (lseq[0] == p_seq[3]))
        && (!blk[1] || (sel[7:4] != 4'd3) || (lseq[1] == p_seq[3]))
        && (!blk[2] || (sel[11:8] != 4'd3) || (lseq[2] == p_seq[3]))
        && (!blk[3] || (sel[15:12] != 4'd3) || (lseq[3] == p_seq[3]))
        && (!blk[4] || (sel[19:16] != 4'd3) || (lseq[4] == p_seq[3]))
        && (!blk[5] || (sel[23:20] != 4'd3) || (lseq[5] == p_seq[3]));
    // U4.rx: subscribers L0.I0 (sel 4), L0.I1 (sel 4), L1.I0 (sel 4), L1.I1 (sel 4), L2.I0 (sel 4), L2.I1 (sel 4)
    assign all_taken[4] = (!blk[0] || (sel[3:0] != 4'd4) || (lseq[0] == p_seq[4]))
        && (!blk[1] || (sel[7:4] != 4'd4) || (lseq[1] == p_seq[4]))
        && (!blk[2] || (sel[11:8] != 4'd4) || (lseq[2] == p_seq[4]))
        && (!blk[3] || (sel[15:12] != 4'd4) || (lseq[3] == p_seq[4]))
        && (!blk[4] || (sel[19:16] != 4'd4) || (lseq[4] == p_seq[4]))
        && (!blk[5] || (sel[23:20] != 4'd4) || (lseq[5] == p_seq[4]));
    // U5.rx: subscribers L0.I0 (sel 5), L0.I1 (sel 5), L1.I0 (sel 5), L1.I1 (sel 5), L2.I0 (sel 5), L2.I1 (sel 5)
    assign all_taken[5] = (!blk[0] || (sel[3:0] != 4'd5) || (lseq[0] == p_seq[5]))
        && (!blk[1] || (sel[7:4] != 4'd5) || (lseq[1] == p_seq[5]))
        && (!blk[2] || (sel[11:8] != 4'd5) || (lseq[2] == p_seq[5]))
        && (!blk[3] || (sel[15:12] != 4'd5) || (lseq[3] == p_seq[5]))
        && (!blk[4] || (sel[19:16] != 4'd5) || (lseq[4] == p_seq[5]))
        && (!blk[5] || (sel[23:20] != 4'd5) || (lseq[5] == p_seq[5]));
    // L0.O0: subscribers L2.I1 (sel 7), U0.tx (sel 0), U1.tx (sel 0), U2.tx (sel 0), U3.tx (sel 0), U4.tx (sel 0), U5.tx (sel 0), HOST_OUT (sel 0)
    assign all_taken[6] = (!blk[5] || (sel[23:20] != 4'd7) || (lseq[5] == p_seq[6]))
        && (!blk[6] || (sel[27:24] != 4'd0) || (lseq[6] == p_seq[6]))
        && (!blk[7] || (sel[31:28] != 4'd0) || (lseq[7] == p_seq[6]))
        && (!blk[8] || (sel[35:32] != 4'd0) || (lseq[8] == p_seq[6]))
        && (!blk[9] || (sel[39:36] != 4'd0) || (lseq[9] == p_seq[6]))
        && (!blk[10] || (sel[43:40] != 4'd0) || (lseq[10] == p_seq[6]))
        && (!blk[11] || (sel[47:44] != 4'd0) || (lseq[11] == p_seq[6]))
        && (!blk[12] || (sel[51:48] != 4'd0) || (lseq[12] == p_seq[6]));
    // L0.O1: subscribers L1.I0 (sel 7), L1.I1 (sel 8), U0.tx (sel 3), U1.tx (sel 3), U2.tx (sel 3), U3.tx (sel 3), U4.tx (sel 3), U5.tx (sel 3), HOST_OUT (sel 3)
    assign all_taken[7] = (!blk[2] || (sel[11:8] != 4'd7) || (lseq[2] == p_seq[7]))
        && (!blk[3] || (sel[15:12] != 4'd8) || (lseq[3] == p_seq[7]))
        && (!blk[6] || (sel[27:24] != 4'd3) || (lseq[6] == p_seq[7]))
        && (!blk[7] || (sel[31:28] != 4'd3) || (lseq[7] == p_seq[7]))
        && (!blk[8] || (sel[35:32] != 4'd3) || (lseq[8] == p_seq[7]))
        && (!blk[9] || (sel[39:36] != 4'd3) || (lseq[9] == p_seq[7]))
        && (!blk[10] || (sel[43:40] != 4'd3) || (lseq[10] == p_seq[7]))
        && (!blk[11] || (sel[47:44] != 4'd3) || (lseq[11] == p_seq[7]))
        && (!blk[12] || (sel[51:48] != 4'd3) || (lseq[12] == p_seq[7]));
    // L1.O0: subscribers L0.I1 (sel 7), U0.tx (sel 1), U1.tx (sel 1), U2.tx (sel 1), U3.tx (sel 1), U4.tx (sel 1), U5.tx (sel 1), HOST_OUT (sel 1)
    assign all_taken[8] = (!blk[1] || (sel[7:4] != 4'd7) || (lseq[1] == p_seq[8]))
        && (!blk[6] || (sel[27:24] != 4'd1) || (lseq[6] == p_seq[8]))
        && (!blk[7] || (sel[31:28] != 4'd1) || (lseq[7] == p_seq[8]))
        && (!blk[8] || (sel[35:32] != 4'd1) || (lseq[8] == p_seq[8]))
        && (!blk[9] || (sel[39:36] != 4'd1) || (lseq[9] == p_seq[8]))
        && (!blk[10] || (sel[43:40] != 4'd1) || (lseq[10] == p_seq[8]))
        && (!blk[11] || (sel[47:44] != 4'd1) || (lseq[11] == p_seq[8]))
        && (!blk[12] || (sel[51:48] != 4'd1) || (lseq[12] == p_seq[8]));
    // L1.O1: subscribers L2.I0 (sel 7), L2.I1 (sel 8), U0.tx (sel 4), U1.tx (sel 4), U2.tx (sel 4), U3.tx (sel 4), U4.tx (sel 4), U5.tx (sel 4), HOST_OUT (sel 4)
    assign all_taken[9] = (!blk[4] || (sel[19:16] != 4'd7) || (lseq[4] == p_seq[9]))
        && (!blk[5] || (sel[23:20] != 4'd8) || (lseq[5] == p_seq[9]))
        && (!blk[6] || (sel[27:24] != 4'd4) || (lseq[6] == p_seq[9]))
        && (!blk[7] || (sel[31:28] != 4'd4) || (lseq[7] == p_seq[9]))
        && (!blk[8] || (sel[35:32] != 4'd4) || (lseq[8] == p_seq[9]))
        && (!blk[9] || (sel[39:36] != 4'd4) || (lseq[9] == p_seq[9]))
        && (!blk[10] || (sel[43:40] != 4'd4) || (lseq[10] == p_seq[9]))
        && (!blk[11] || (sel[47:44] != 4'd4) || (lseq[11] == p_seq[9]))
        && (!blk[12] || (sel[51:48] != 4'd4) || (lseq[12] == p_seq[9]));
    // L2.O0: subscribers L1.I1 (sel 7), U0.tx (sel 2), U1.tx (sel 2), U2.tx (sel 2), U3.tx (sel 2), U4.tx (sel 2), U5.tx (sel 2), HOST_OUT (sel 2)
    assign all_taken[10] = (!blk[3] || (sel[15:12] != 4'd7) || (lseq[3] == p_seq[10]))
        && (!blk[6] || (sel[27:24] != 4'd2) || (lseq[6] == p_seq[10]))
        && (!blk[7] || (sel[31:28] != 4'd2) || (lseq[7] == p_seq[10]))
        && (!blk[8] || (sel[35:32] != 4'd2) || (lseq[8] == p_seq[10]))
        && (!blk[9] || (sel[39:36] != 4'd2) || (lseq[9] == p_seq[10]))
        && (!blk[10] || (sel[43:40] != 4'd2) || (lseq[10] == p_seq[10]))
        && (!blk[11] || (sel[47:44] != 4'd2) || (lseq[11] == p_seq[10]))
        && (!blk[12] || (sel[51:48] != 4'd2) || (lseq[12] == p_seq[10]));
    // L2.O1: subscribers L0.I0 (sel 7), L0.I1 (sel 8), U0.tx (sel 5), U1.tx (sel 5), U2.tx (sel 5), U3.tx (sel 5), U4.tx (sel 5), U5.tx (sel 5), HOST_OUT (sel 5)
    assign all_taken[11] = (!blk[0] || (sel[3:0] != 4'd7) || (lseq[0] == p_seq[11]))
        && (!blk[1] || (sel[7:4] != 4'd8) || (lseq[1] == p_seq[11]))
        && (!blk[6] || (sel[27:24] != 4'd5) || (lseq[6] == p_seq[11]))
        && (!blk[7] || (sel[31:28] != 4'd5) || (lseq[7] == p_seq[11]))
        && (!blk[8] || (sel[35:32] != 4'd5) || (lseq[8] == p_seq[11]))
        && (!blk[9] || (sel[39:36] != 4'd5) || (lseq[9] == p_seq[11]))
        && (!blk[10] || (sel[43:40] != 4'd5) || (lseq[10] == p_seq[11]))
        && (!blk[11] || (sel[47:44] != 4'd5) || (lseq[11] == p_seq[11]))
        && (!blk[12] || (sel[51:48] != 4'd5) || (lseq[12] == p_seq[11]));
    // HOST_IN: subscribers L0.I0 (sel 6), L0.I1 (sel 6), L1.I0 (sel 6), L1.I1 (sel 6), L2.I0 (sel 6), L2.I1 (sel 6), U0.tx (sel 6), U1.tx (sel 6), U2.tx (sel 6), U3.tx (sel 6), U4.tx (sel 6), U5.tx (sel 6)
    assign all_taken[12] = (!blk[0] || (sel[3:0] != 4'd6) || (lseq[0] == p_seq[12]))
        && (!blk[1] || (sel[7:4] != 4'd6) || (lseq[1] == p_seq[12]))
        && (!blk[2] || (sel[11:8] != 4'd6) || (lseq[2] == p_seq[12]))
        && (!blk[3] || (sel[15:12] != 4'd6) || (lseq[3] == p_seq[12]))
        && (!blk[4] || (sel[19:16] != 4'd6) || (lseq[4] == p_seq[12]))
        && (!blk[5] || (sel[23:20] != 4'd6) || (lseq[5] == p_seq[12]))
        && (!blk[6] || (sel[27:24] != 4'd6) || (lseq[6] == p_seq[12]))
        && (!blk[7] || (sel[31:28] != 4'd6) || (lseq[7] == p_seq[12]))
        && (!blk[8] || (sel[35:32] != 4'd6) || (lseq[8] == p_seq[12]))
        && (!blk[9] || (sel[39:36] != 4'd6) || (lseq[9] == p_seq[12]))
        && (!blk[10] || (sel[43:40] != 4'd6) || (lseq[10] == p_seq[12]))
        && (!blk[11] || (sel[47:44] != 4'd6) || (lseq[11] == p_seq[12]));
endmodule
