// GENERATED by tools/gen/gen.py from spec/tripwire.yaml. DO NOT EDIT.
// Channel fabric (ARCHITECTURE.md §4): the consumer ports (trw_chan_port.v) with their legal-source
// multiplexers (§4.6) and each producer's release term (§4.4, §14 F3). The producer registers belong
// to their owners (trw_chan_prod.v for pin units and HOST_IN; trw_lane.v for lane outputs).
//
// Timing contract: all_taken[p] is combinational from registered state only (the ports' en, tap, sel,
// last_seq and the producer's seq), so a take never reaches a producer in the same clock (F3).
// Configuration: cfg_we[c] writes port c from the shared cfg_* fields (F5). port_state[c] =
// {accept, sel, tap, en} for host readback.
//
// Producers: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 L0.O0, 7 L0.O1, 8 L1.O0, 9 L1.O1, 10 L2.O0, 11 L2.O1, 12 HOST_IN
// Consumers: 0 L0.I0, 1 L0.I1, 2 L1.I0, 3 L1.I1, 4 L2.I0, 5 L2.I1, 6 U0.tx, 7 U1.tx, 8 U2.tx, 9 U3.tx, 10 U4.tx, 11 U5.tx, 12 HOST_OUT
`default_nettype none

module trw_fabric (
    input  wire clk,
    input  wire rst_n,
    input  wire [12:0] p_valid,
    input  wire [12:0] p_seq,
    input  wire [12:0] p_load,
    input  wire [233:0] p_tok,
    output wire [12:0] all_taken,
    input  wire [12:0] take,
    output wire [12:0] avail,
    output wire [233:0] head,
    input  wire [12:0] cfg_we,
    input  wire cfg_en,
    input  wire cfg_tap,
    input  wire [3:0] cfg_sel,
    input  wire [3:0] cfg_accept,
    input  wire [12:0] clr_dropped,
    output wire [129:0] port_state,
    output wire [103:0] dropped
);
    wire [12:0] en, tap, blk, lseq;
    wire [51:0] sel, acc;

    // 0 L0.I0: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L2.O1
    trw_chan_port #(.N(8)) u_c0 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[0]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[0]),
        .src_valid ({p_valid[11], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[11], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[11], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[215:198], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[0]), .avail (avail[0]), .head (head[17:0]),
        .en (en[0]), .tap (tap[0]), .sel (sel[3:0]), .accept (acc[3:0]),
        .blocking (blk[0]), .last_seq (lseq[0]), .dropped (dropped[7:0])
    );
    assign port_state[9:0] = {acc[3:0], sel[3:0], tap[0], en[0]};

    // 1 L0.I1: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L1.O0, 8 L2.O1
    trw_chan_port #(.N(9)) u_c1 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[1]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[1]),
        .src_valid ({p_valid[11], p_valid[8], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[11], p_seq[8], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[11], p_load[8], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[215:198], p_tok[161:144], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[1]), .avail (avail[1]), .head (head[35:18]),
        .en (en[1]), .tap (tap[1]), .sel (sel[7:4]), .accept (acc[7:4]),
        .blocking (blk[1]), .last_seq (lseq[1]), .dropped (dropped[15:8])
    );
    assign port_state[19:10] = {acc[7:4], sel[7:4], tap[1], en[1]};

    // 2 L1.I0: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L0.O1
    trw_chan_port #(.N(8)) u_c2 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[2]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[2]),
        .src_valid ({p_valid[7], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[7], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[7], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[143:126], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[2]), .avail (avail[2]), .head (head[53:36]),
        .en (en[2]), .tap (tap[2]), .sel (sel[11:8]), .accept (acc[11:8]),
        .blocking (blk[2]), .last_seq (lseq[2]), .dropped (dropped[23:16])
    );
    assign port_state[29:20] = {acc[11:8], sel[11:8], tap[2], en[2]};

    // 3 L1.I1: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L2.O0, 8 L0.O1
    trw_chan_port #(.N(9)) u_c3 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[3]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[3]),
        .src_valid ({p_valid[7], p_valid[10], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[7], p_seq[10], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[7], p_load[10], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[143:126], p_tok[197:180], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[3]), .avail (avail[3]), .head (head[71:54]),
        .en (en[3]), .tap (tap[3]), .sel (sel[15:12]), .accept (acc[15:12]),
        .blocking (blk[3]), .last_seq (lseq[3]), .dropped (dropped[31:24])
    );
    assign port_state[39:30] = {acc[15:12], sel[15:12], tap[3], en[3]};

    // 4 L2.I0: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L1.O1
    trw_chan_port #(.N(8)) u_c4 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[4]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[4]),
        .src_valid ({p_valid[9], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[9], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[9], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[179:162], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[4]), .avail (avail[4]), .head (head[89:72]),
        .en (en[4]), .tap (tap[4]), .sel (sel[19:16]), .accept (acc[19:16]),
        .blocking (blk[4]), .last_seq (lseq[4]), .dropped (dropped[39:32])
    );
    assign port_state[49:40] = {acc[19:16], sel[19:16], tap[4], en[4]};

    // 5 L2.I1: 0 U0.rx, 1 U1.rx, 2 U2.rx, 3 U3.rx, 4 U4.rx, 5 U5.rx, 6 HOST_IN, 7 L0.O0, 8 L1.O1
    trw_chan_port #(.N(9)) u_c5 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[5]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[5]),
        .src_valid ({p_valid[9], p_valid[6], p_valid[12], p_valid[5], p_valid[4], p_valid[3], p_valid[2], p_valid[1], p_valid[0]}),
        .src_seq ({p_seq[9], p_seq[6], p_seq[12], p_seq[5], p_seq[4], p_seq[3], p_seq[2], p_seq[1], p_seq[0]}),
        .src_load ({p_load[9], p_load[6], p_load[12], p_load[5], p_load[4], p_load[3], p_load[2], p_load[1], p_load[0]}),
        .src_tok ({p_tok[179:162], p_tok[125:108], p_tok[233:216], p_tok[107:90], p_tok[89:72], p_tok[71:54], p_tok[53:36], p_tok[35:18], p_tok[17:0]}),
        .take (take[5]), .avail (avail[5]), .head (head[107:90]),
        .en (en[5]), .tap (tap[5]), .sel (sel[23:20]), .accept (acc[23:20]),
        .blocking (blk[5]), .last_seq (lseq[5]), .dropped (dropped[47:40])
    );
    assign port_state[59:50] = {acc[23:20], sel[23:20], tap[5], en[5]};

    // 6 U0.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    trw_chan_port #(.N(7)) u_c6 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[6]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[6]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[6]), .avail (avail[6]), .head (head[125:108]),
        .en (en[6]), .tap (tap[6]), .sel (sel[27:24]), .accept (acc[27:24]),
        .blocking (blk[6]), .last_seq (lseq[6]), .dropped (dropped[55:48])
    );
    assign port_state[69:60] = {acc[27:24], sel[27:24], tap[6], en[6]};

    // 7 U1.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    trw_chan_port #(.N(7)) u_c7 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[7]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[7]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[7]), .avail (avail[7]), .head (head[143:126]),
        .en (en[7]), .tap (tap[7]), .sel (sel[31:28]), .accept (acc[31:28]),
        .blocking (blk[7]), .last_seq (lseq[7]), .dropped (dropped[63:56])
    );
    assign port_state[79:70] = {acc[31:28], sel[31:28], tap[7], en[7]};

    // 8 U2.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    trw_chan_port #(.N(7)) u_c8 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[8]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[8]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[8]), .avail (avail[8]), .head (head[161:144]),
        .en (en[8]), .tap (tap[8]), .sel (sel[35:32]), .accept (acc[35:32]),
        .blocking (blk[8]), .last_seq (lseq[8]), .dropped (dropped[71:64])
    );
    assign port_state[89:80] = {acc[35:32], sel[35:32], tap[8], en[8]};

    // 9 U3.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    trw_chan_port #(.N(7)) u_c9 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[9]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[9]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[9]), .avail (avail[9]), .head (head[179:162]),
        .en (en[9]), .tap (tap[9]), .sel (sel[39:36]), .accept (acc[39:36]),
        .blocking (blk[9]), .last_seq (lseq[9]), .dropped (dropped[79:72])
    );
    assign port_state[99:90] = {acc[39:36], sel[39:36], tap[9], en[9]};

    // 10 U4.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    trw_chan_port #(.N(7)) u_c10 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[10]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[10]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[10]), .avail (avail[10]), .head (head[197:180]),
        .en (en[10]), .tap (tap[10]), .sel (sel[43:40]), .accept (acc[43:40]),
        .blocking (blk[10]), .last_seq (lseq[10]), .dropped (dropped[87:80])
    );
    assign port_state[109:100] = {acc[43:40], sel[43:40], tap[10], en[10]};

    // 11 U5.tx: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 HOST_IN
    trw_chan_port #(.N(7)) u_c11 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[11]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[11]),
        .src_valid ({p_valid[12], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[12], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[12], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[233:216], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[11]), .avail (avail[11]), .head (head[215:198]),
        .en (en[11]), .tap (tap[11]), .sel (sel[47:44]), .accept (acc[47:44]),
        .blocking (blk[11]), .last_seq (lseq[11]), .dropped (dropped[95:88])
    );
    assign port_state[119:110] = {acc[47:44], sel[47:44], tap[11], en[11]};

    // 12 HOST_OUT: 0 L0.O0, 1 L1.O0, 2 L2.O0, 3 L0.O1, 4 L1.O1, 5 L2.O1, 6 U0.rx, 7 U1.rx
    trw_chan_port #(.N(8)) u_c12 (
        .clk (clk), .rst_n (rst_n),
        .cfg_we (cfg_we[12]), .cfg_en (cfg_en), .cfg_tap (cfg_tap), .cfg_sel (cfg_sel),
        .cfg_accept (cfg_accept), .clr_dropped (clr_dropped[12]),
        .src_valid ({p_valid[1], p_valid[0], p_valid[11], p_valid[9], p_valid[7], p_valid[10], p_valid[8], p_valid[6]}),
        .src_seq ({p_seq[1], p_seq[0], p_seq[11], p_seq[9], p_seq[7], p_seq[10], p_seq[8], p_seq[6]}),
        .src_load ({p_load[1], p_load[0], p_load[11], p_load[9], p_load[7], p_load[10], p_load[8], p_load[6]}),
        .src_tok ({p_tok[35:18], p_tok[17:0], p_tok[215:198], p_tok[179:162], p_tok[143:126], p_tok[197:180], p_tok[161:144], p_tok[125:108]}),
        .take (take[12]), .avail (avail[12]), .head (head[233:216]),
        .en (en[12]), .tap (tap[12]), .sel (sel[51:48]), .accept (acc[51:48]),
        .blocking (blk[12]), .last_seq (lseq[12]), .dropped (dropped[103:96])
    );
    assign port_state[129:120] = {acc[51:48], sel[51:48], tap[12], en[12]};

    // U0.rx: subscribers L0.I0 (sel 0), L0.I1 (sel 0), L1.I0 (sel 0), L1.I1 (sel 0), L2.I0 (sel 0), L2.I1 (sel 0), HOST_OUT (sel 6)
    assign all_taken[0] = (!blk[0] || (sel[3:0] != 4'd0) || (lseq[0] == p_seq[0]))
        && (!blk[1] || (sel[7:4] != 4'd0) || (lseq[1] == p_seq[0]))
        && (!blk[2] || (sel[11:8] != 4'd0) || (lseq[2] == p_seq[0]))
        && (!blk[3] || (sel[15:12] != 4'd0) || (lseq[3] == p_seq[0]))
        && (!blk[4] || (sel[19:16] != 4'd0) || (lseq[4] == p_seq[0]))
        && (!blk[5] || (sel[23:20] != 4'd0) || (lseq[5] == p_seq[0]))
        && (!blk[12] || (sel[51:48] != 4'd6) || (lseq[12] == p_seq[0]));
    // U1.rx: subscribers L0.I0 (sel 1), L0.I1 (sel 1), L1.I0 (sel 1), L1.I1 (sel 1), L2.I0 (sel 1), L2.I1 (sel 1), HOST_OUT (sel 7)
    assign all_taken[1] = (!blk[0] || (sel[3:0] != 4'd1) || (lseq[0] == p_seq[1]))
        && (!blk[1] || (sel[7:4] != 4'd1) || (lseq[1] == p_seq[1]))
        && (!blk[2] || (sel[11:8] != 4'd1) || (lseq[2] == p_seq[1]))
        && (!blk[3] || (sel[15:12] != 4'd1) || (lseq[3] == p_seq[1]))
        && (!blk[4] || (sel[19:16] != 4'd1) || (lseq[4] == p_seq[1]))
        && (!blk[5] || (sel[23:20] != 4'd1) || (lseq[5] == p_seq[1]))
        && (!blk[12] || (sel[51:48] != 4'd7) || (lseq[12] == p_seq[1]));
    // U2.rx: subscribers L0.I0 (sel 2), L0.I1 (sel 2), L1.I0 (sel 2), L1.I1 (sel 2), L2.I0 (sel 2), L2.I1 (sel 2)
    assign all_taken[2] = (!blk[0] || (sel[3:0] != 4'd2) || (lseq[0] == p_seq[2]))
        && (!blk[1] || (sel[7:4] != 4'd2) || (lseq[1] == p_seq[2]))
        && (!blk[2] || (sel[11:8] != 4'd2) || (lseq[2] == p_seq[2]))
        && (!blk[3] || (sel[15:12] != 4'd2) || (lseq[3] == p_seq[2]))
        && (!blk[4] || (sel[19:16] != 4'd2) || (lseq[4] == p_seq[2]))
        && (!blk[5] || (sel[23:20] != 4'd2) || (lseq[5] == p_seq[2]));
    // U3.rx: subscribers L0.I0 (sel 3), L0.I1 (sel 3), L1.I0 (sel 3), L1.I1 (sel 3), L2.I0 (sel 3), L2.I1 (sel 3)
    assign all_taken[3] = (!blk[0] || (sel[3:0] != 4'd3) || (lseq[0] == p_seq[3]))
        && (!blk[1] || (sel[7:4] != 4'd3) || (lseq[1] == p_seq[3]))
        && (!blk[2] || (sel[11:8] != 4'd3) || (lseq[2] == p_seq[3]))
        && (!blk[3] || (sel[15:12] != 4'd3) || (lseq[3] == p_seq[3]))
        && (!blk[4] || (sel[19:16] != 4'd3) || (lseq[4] == p_seq[3]))
        && (!blk[5] || (sel[23:20] != 4'd3) || (lseq[5] == p_seq[3]));
    // U4.rx: subscribers L0.I0 (sel 4), L0.I1 (sel 4), L1.I0 (sel 4), L1.I1 (sel 4), L2.I0 (sel 4), L2.I1 (sel 4)
    assign all_taken[4] = (!blk[0] || (sel[3:0] != 4'd4) || (lseq[0] == p_seq[4]))
        && (!blk[1] || (sel[7:4] != 4'd4) || (lseq[1] == p_seq[4]))
        && (!blk[2] || (sel[11:8] != 4'd4) || (lseq[2] == p_seq[4]))
        && (!blk[3] || (sel[15:12] != 4'd4) || (lseq[3] == p_seq[4]))
        && (!blk[4] || (sel[19:16] != 4'd4) || (lseq[4] == p_seq[4]))
        && (!blk[5] || (sel[23:20] != 4'd4) || (lseq[5] == p_seq[4]));
    // U5.rx: subscribers L0.I0 (sel 5), L0.I1 (sel 5), L1.I0 (sel 5), L1.I1 (sel 5), L2.I0 (sel 5), L2.I1 (sel 5)
    assign all_taken[5] = (!blk[0] || (sel[3:0] != 4'd5) || (lseq[0] == p_seq[5]))
        && (!blk[1] || (sel[7:4] != 4'd5) || (lseq[1] == p_seq[5]))
        && (!blk[2] || (sel[11:8] != 4'd5) || (lseq[2] == p_seq[5]))
        && (!blk[3] || (sel[15:12] != 4'd5) || (lseq[3] == p_seq[5]))
        && (!blk[4] || (sel[19:16] != 4'd5) || (lseq[4] == p_seq[5]))
        && (!blk[5] || (sel[23:20] != 4'd5) || (lseq[5] == p_seq[5]));
    // L0.O0: subscribers L2.I1 (sel 7), U0.tx (sel 0), U1.tx (sel 0), U2.tx (sel 0), U3.tx (sel 0), U4.tx (sel 0), U5.tx (sel 0), HOST_OUT (sel 0)
    assign all_taken[6] = (!blk[5] || (sel[23:20] != 4'd7) || (lseq[5] == p_seq[6]))
        && (!blk[6] || (sel[27:24] != 4'd0) || (lseq[6] == p_seq[6]))
        && (!blk[7] || (sel[31:28] != 4'd0) || (lseq[7] == p_seq[6]))
        && (!blk[8] || (sel[35:32] != 4'd0) || (lseq[8] == p_seq[6]))
        && (!blk[9] || (sel[39:36] != 4'd0) || (lseq[9] == p_seq[6]))
        && (!blk[10] || (sel[43:40] != 4'd0) || (lseq[10] == p_seq[6]))
        && (!blk[11] || (sel[47:44] != 4'd0) || (lseq[11] == p_seq[6]))
        && (!blk[12] || (sel[51:48] != 4'd0) || (lseq[12] == p_seq[6]));
    // L0.O1: subscribers L1.I0 (sel 7), L1.I1 (sel 8), U0.tx (sel 3), U1.tx (sel 3), U2.tx (sel 3), U3.tx (sel 3), U4.tx (sel 3), U5.tx (sel 3), HOST_OUT (sel 3)
    assign all_taken[7] = (!blk[2] || (sel[11:8] != 4'd7) || (lseq[2] == p_seq[7]))
        && (!blk[3] || (sel[15:12] != 4'd8) || (lseq[3] == p_seq[7]))
        && (!blk[6] || (sel[27:24] != 4'd3) || (lseq[6] == p_seq[7]))
        && (!blk[7] || (sel[31:28] != 4'd3) || (lseq[7] == p_seq[7]))
        && (!blk[8] || (sel[35:32] != 4'd3) || (lseq[8] == p_seq[7]))
        && (!blk[9] || (sel[39:36] != 4'd3) || (lseq[9] == p_seq[7]))
        && (!blk[10] || (sel[43:40] != 4'd3) || (lseq[10] == p_seq[7]))
        && (!blk[11] || (sel[47:44] != 4'd3) || (lseq[11] == p_seq[7]))
        && (!blk[12] || (sel[51:48] != 4'd3) || (lseq[12] == p_seq[7]));
    // L1.O0: subscribers L0.I1 (sel 7), U0.tx (sel 1), U1.tx (sel 1), U2.tx (sel 1), U3.tx (sel 1), U4.tx (sel 1), U5.tx (sel 1), HOST_OUT (sel 1)
    assign all_taken[8] = (!blk[1] || (sel[7:4] != 4'd7) || (lseq[1] == p_seq[8]))
        && (!blk[6] || (sel[27:24] != 4'd1) || (lseq[6] == p_seq[8]))
        && (!blk[7] || (sel[31:28] != 4'd1) || (lseq[7] == p_seq[8]))
        && (!blk[8] || (sel[35:32] != 4'd1) || (lseq[8] == p_seq[8]))
        && (!blk[9] || (sel[39:36] != 4'd1) || (lseq[9] == p_seq[8]))
        && (!blk[10] || (sel[43:40] != 4'd1) || (lseq[10] == p_seq[8]))
        && (!blk[11] || (sel[47:44] != 4'd1) || (lseq[11] == p_seq[8]))
        && (!blk[12] || (sel[51:48] != 4'd1) || (lseq[12] == p_seq[8]));
    // L1.O1: subscribers L2.I0 (sel 7), L2.I1 (sel 8), U0.tx (sel 4), U1.tx (sel 4), U2.tx (sel 4), U3.tx (sel 4), U4.tx (sel 4), U5.tx (sel 4), HOST_OUT (sel 4)
    assign all_taken[9] = (!blk[4] || (sel[19:16] != 4'd7) || (lseq[4] == p_seq[9]))
        && (!blk[5] || (sel[23:20] != 4'd8) || (lseq[5] == p_seq[9]))
        && (!blk[6] || (sel[27:24] != 4'd4) || (lseq[6] == p_seq[9]))
        && (!blk[7] || (sel[31:28] != 4'd4) || (lseq[7] == p_seq[9]))
        && (!blk[8] || (sel[35:32] != 4'd4) || (lseq[8] == p_seq[9]))
        && (!blk[9] || (sel[39:36] != 4'd4) || (lseq[9] == p_seq[9]))
        && (!blk[10] || (sel[43:40] != 4'd4) || (lseq[10] == p_seq[9]))
        && (!blk[11] || (sel[47:44] != 4'd4) || (lseq[11] == p_seq[9]))
        && (!blk[12] || (sel[51:48] != 4'd4) || (lseq[12] == p_seq[9]));
    // L2.O0: subscribers L1.I1 (sel 7), U0.tx (sel 2), U1.tx (sel 2), U2.tx (sel 2), U3.tx (sel 2), U4.tx (sel 2), U5.tx (sel 2), HOST_OUT (sel 2)
    assign all_taken[10] = (!blk[3] || (sel[15:12] != 4'd7) || (lseq[3] == p_seq[10]))
        && (!blk[6] || (sel[27:24] != 4'd2) || (lseq[6] == p_seq[10]))
        && (!blk[7] || (sel[31:28] != 4'd2) || (lseq[7] == p_seq[10]))
        && (!blk[8] || (sel[35:32] != 4'd2) || (lseq[8] == p_seq[10]))
        && (!blk[9] || (sel[39:36] != 4'd2) || (lseq[9] == p_seq[10]))
        && (!blk[10] || (sel[43:40] != 4'd2) || (lseq[10] == p_seq[10]))
        && (!blk[11] || (sel[47:44] != 4'd2) || (lseq[11] == p_seq[10]))
        && (!blk[12] || (sel[51:48] != 4'd2) || (lseq[12] == p_seq[10]));
    // L2.O1: subscribers L0.I0 (sel 7), L0.I1 (sel 8), U0.tx (sel 5), U1.tx (sel 5), U2.tx (sel 5), U3.tx (sel 5), U4.tx (sel 5), U5.tx (sel 5), HOST_OUT (sel 5)
    assign all_taken[11] = (!blk[0] || (sel[3:0] != 4'd7) || (lseq[0] == p_seq[11]))
        && (!blk[1] || (sel[7:4] != 4'd8) || (lseq[1] == p_seq[11]))
        && (!blk[6] || (sel[27:24] != 4'd5) || (lseq[6] == p_seq[11]))
        && (!blk[7] || (sel[31:28] != 4'd5) || (lseq[7] == p_seq[11]))
        && (!blk[8] || (sel[35:32] != 4'd5) || (lseq[8] == p_seq[11]))
        && (!blk[9] || (sel[39:36] != 4'd5) || (lseq[9] == p_seq[11]))
        && (!blk[10] || (sel[43:40] != 4'd5) || (lseq[10] == p_seq[11]))
        && (!blk[11] || (sel[47:44] != 4'd5) || (lseq[11] == p_seq[11]))
        && (!blk[12] || (sel[51:48] != 4'd5) || (lseq[12] == p_seq[11]));
    // HOST_IN: subscribers L0.I0 (sel 6), L0.I1 (sel 6), L1.I0 (sel 6), L1.I1 (sel 6), L2.I0 (sel 6), L2.I1 (sel 6), U0.tx (sel 6), U1.tx (sel 6), U2.tx (sel 6), U3.tx (sel 6), U4.tx (sel 6), U5.tx (sel 6)
    assign all_taken[12] = (!blk[0] || (sel[3:0] != 4'd6) || (lseq[0] == p_seq[12]))
        && (!blk[1] || (sel[7:4] != 4'd6) || (lseq[1] == p_seq[12]))
        && (!blk[2] || (sel[11:8] != 4'd6) || (lseq[2] == p_seq[12]))
        && (!blk[3] || (sel[15:12] != 4'd6) || (lseq[3] == p_seq[12]))
        && (!blk[4] || (sel[19:16] != 4'd6) || (lseq[4] == p_seq[12]))
        && (!blk[5] || (sel[23:20] != 4'd6) || (lseq[5] == p_seq[12]))
        && (!blk[6] || (sel[27:24] != 4'd6) || (lseq[6] == p_seq[12]))
        && (!blk[7] || (sel[31:28] != 4'd6) || (lseq[7] == p_seq[12]))
        && (!blk[8] || (sel[35:32] != 4'd6) || (lseq[8] == p_seq[12]))
        && (!blk[9] || (sel[39:36] != 4'd6) || (lseq[9] == p_seq[12]))
        && (!blk[10] || (sel[43:40] != 4'd6) || (lseq[10] == p_seq[12]))
        && (!blk[11] || (sel[47:44] != 4'd6) || (lseq[11] == p_seq[12]));
endmodule
